package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import com.facebook.ads.AdError;
import com.facebook.appevents.integrity.IntegrityManager;
import com.google.android.gms.ads.internal.util.zzbr;
import com.telguarder.ApplicationConstants;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
/* loaded from: classes2-dex2jar.jar:com/google/android/gms/internal/ads/zzabp.class */
public final class zzabp {
    private static final zzaba<String> zzcst;
    public static final zzaba<String> zzcmj = zzaba.zza(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    private static final zzaba<String> zzcmk = zzaba.zza(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    private static final zzacx<Boolean> zzcml = zzadn.zzcml;
    private static final zzaba<Integer> zzcmm = zzaba.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzaba<String> zzcmn = zzaba.zza(1, "gads:video_exo_player:version", "3");
    public static final zzaba<Integer> zzcmo = zzaba.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzaba<Integer> zzcmp = zzaba.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzaba<Integer> zzcmq = zzaba.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzaba<Integer> zzcmr = zzaba.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzaba<Integer> zzcms = zzaba.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final zzaba<Integer> zzcmt = zzaba.zza(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final zzaba<String> zzcmu = zzaba.zza(1, "gads:video_exo_player:precache_exceptions", "");
    public static final zzaba<Integer> zzcmv = zzaba.zza(1, "gads:video_exo_player:min_retry_count", -1);
    public static final zzaba<Boolean> zzcmw = zzaba.zza(1, "gads:video_exo_player:fmp4_extractor_enabled", (Boolean) false);
    public static final zzaba<Integer> zzcmx = zzaba.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzaba<Integer> zzcmy = zzaba.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzaba<Integer> zzcmz = zzaba.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzaba<Long> zzcna = zzaba.zzb(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzaba<Long> zzcnb = zzaba.zzb(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzaba<Integer> zzcnc = zzaba.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzaba<String> zzcnd = zzaba.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzaba<Long> zzcne = zzaba.zzb(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzaba<Boolean> zzcnf = zzaba.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzaba<Long> zzcng = zzaba.zzb(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzaba<Boolean> zzcnh = zzaba.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzaba<Integer> zzcni = zzaba.zza(1, "gads:video:spinner:scale", 4);
    public static final zzaba<Long> zzcnj = zzaba.zzb(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzaba<Boolean> zzcnk = zzaba.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzaba<Boolean> zzcnl = zzaba.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzaba<String> zzcnm = zzaba.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzaba<Integer> zzcnn = zzaba.zza(1, "gads:video:codec_query_minimum_version", 16);
    public static final zzaba<Boolean> zzcno = zzaba.zza(1, "gads:video:set_black_background", (Boolean) false);
    public static final zzaba<String> zzcnp = zzaba.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final zzaba<String> zzcnq = zzaba.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final zzaba<String> zzcnr = zzaba.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final zzaba<String> zzcns = zzaba.zza(1, "gad:mraid:version", "3.0");
    public static final zzaba<Boolean> zzcnt = zzaba.zza(1, "gads:mraid:expanded_interstitial_fix", (Boolean) false);
    public static final zzaba<Boolean> zzcnu = zzaba.zza(1, "gads:mraid:initial_size_fallback", (Boolean) false);
    public static final zzaba<Integer> zzcnv = zzaba.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzaba<Integer> zzcnw = zzaba.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzaba<Integer> zzcnx = zzaba.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzaba<String> zzcny = zzaba.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzaba<String> zzcnz = zzaba.zza(1, "gads:content_fetch_exclude_view_tag", IntegrityManager.INTEGRITY_TYPE_NONE);
    public static final zzaba<Boolean> zzcoa = zzaba.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzaba<Boolean> zzcob = zzaba.zza(1, "gads:content_fetch_enable_new_content_score", (Boolean) false);
    public static final zzaba<Boolean> zzcoc = zzaba.zza(1, "gads:content_fetch_enable_serve_once", (Boolean) false);
    public static final zzaba<Boolean> zzcod = zzaba.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzaba<String> zzcoe = zzaba.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzaba<String> zzcof = zzaba.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    public static final zzaba<Boolean> zzcog = zzaba.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzaba<String> zzcoh = zzaba.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzaba<Long> zzcoi = zzaba.zzb(1, "gads:sai:timeout_ms", -1);
    public static final zzaba<Integer> zzcoj = zzaba.zza(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzaba<Boolean> zzcok = zzaba.zza(1, "gads:sai:app_measurement_enabled3", (Boolean) false);
    public static final zzaba<Integer> zzcol = zzaba.zza(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final zzaba<Boolean> zzcom = zzaba.zza(1, "gads:sai:force_through_reflection", (Boolean) true);
    public static final zzaba<Boolean> zzcon = zzaba.zza(1, "gads:sai:gmscore_availability_check_disabled", (Boolean) false);
    public static final zzaba<Boolean> zzcoo = zzaba.zza(1, "gads:sai:logging_disabled_for_drx", (Boolean) false);
    public static final zzaba<Boolean> zzcop = zzaba.zza(1, "gads:sai:app_measurement_npa_enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcoq = zzaba.zza(1, "gads:idless:idless_disables_attestation", (Boolean) true);
    public static final zzaba<Boolean> zzcor = zzaba.zza(1, "gads:idless:app_measurement_idless_enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcos = zzaba.zza(1, "gads:idless:internal_state_enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcot = zzaba.zza(1, "gads:idless:idless_disables_offline_ads_signalling", (Boolean) true);
    public static final zzaba<String> zzcou = zzaba.zza(1, "gads:idless:cookie_modification", "=; Max-Age=-1; path=/; domain=.doubleclick.net");
    public static final zzaba<Boolean> zzcov = zzaba.zza(1, "gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcow = zzaba.zza(1, "gads:interstitial:foreground_report:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcox = zzaba.zza(1, "gads:interstitial:default_immersive", (Boolean) false);
    public static final zzaba<Boolean> zzcoy = zzaba.zza(1, "gads:webview:error_web_response:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcoz = zzaba.zza(1, "gads:webview:pause_interstitial:enabled", (Boolean) true);
    private static final zzaba<Boolean> zzcpa = zzaba.zza(1, "gads:rsku:webviewgone:kill_process:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcpb = zzaba.zza(1, "gads:webviewgone:kill_process:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcpc = zzaba.zza(1, "gads:rsku:webviewgone:new_onshow:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcpd = zzaba.zza(1, "gads:webviewgone:new_onshow:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcpe = zzaba.zza(1, "gads:webview:pause_resume:enabled", (Boolean) true);
    public static final zzaba<String> zzcpf = zzaba.zza(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
    private static final zzaba<Boolean> zzcpg = zzaba.zza(1, "gads:new_rewarded_ad:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcph = zzaba.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    private static final zzaba<Long> zzcpi = zzaba.zzb(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzaba<Boolean> zzcpj = zzaba.zza(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcpk = zzaba.zza(1, "gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
    public static final zzaba<Long> zzcpl = zzaba.zzb(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzaba<Long> zzcpm = zzaba.zzb(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzaba<Boolean> zzcpn = zzaba.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzaba<Long> zzcpo = zzaba.zzb(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzaba<Boolean> zzcpp = zzaba.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzaba<Long> zzcpq = zzaba.zzb(1, "gads:ad_overlay:delay_page_close_timeout_ms", ApplicationConstants.CALL_WIDGET_TOOLTIP_HIDE_DELAY);
    public static final zzaba<Boolean> zzcpr = zzaba.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcps = zzaba.zza(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcpt = zzaba.zza(1, "gads:use_system_ui_for_fullscreen:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcpu = zzaba.zza(1, "gads:ad_overlay:collect_cutout_info:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcpv = zzaba.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final zzaba<String> zzcpw = zzaba.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzaba<Integer> zzcpx = zzaba.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzaba<Integer> zzcpy = zzaba.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzaba<Boolean> zzcpz = zzaba.zza(1, "gads:delay_banner_renderer:enabled", (Boolean) true);
    private static final zzaba<Boolean> zzcqa = zzaba.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcqb = zzaba.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    private static final zzaba<String> zzcqc = zzaba.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    private static final zzaba<String> zzcqd = zzaba.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    private static final zzaba<Integer> zzcqe = zzaba.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    private static final zzaba<Integer> zzcqf = zzaba.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    private static final zzaba<Integer> zzcqg = zzaba.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    private static final zzaba<String> zzcqh = zzaba.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    private static final zzaba<Integer> zzcqi = zzaba.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    private static final zzaba<Integer> zzcqj = zzaba.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    private static final zzaba<Long> zzcqk = zzaba.zzb(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    private static final zzaba<Long> zzcql = zzaba.zzb(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    private static final zzaba<Float> zzcqm = zzaba.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    private static final zzaba<Float> zzcqn = zzaba.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzaba<String> zzcqo = zzaba.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzaba<String> zzcqp = zzaba.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzaba<Boolean> zzcqq = zzaba.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzaba<Long> zzcqr = zzaba.zzb(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzaba<Long> zzcqs = zzaba.zzb(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final zzaba<Boolean> zzcqt = zzaba.zza(1, "gads:position_watcher:enable_scroll_aware_ads", (Boolean) false);
    public static final zzaba<Boolean> zzcqu = zzaba.zza(1, "gads:position_watcher:send_scroll_data", (Boolean) false);
    private static final zzaba<Boolean> zzcqv = zzaba.zza(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcqw = zzaba.zza(1, "gads:extra_sdk_versions_for_crash_reports:enabled", (Boolean) true);
    public static final zzaba<String> zzcqx = zzaba.zza(1, "gads:logged_adapter_version_classes", "");
    public static final zzaba<Long> zzcqy = zzaba.zzb(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final zzaba<Boolean> zzcqz = zzaba.zza(1, "gads:rtb_signal:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcra = zzaba.zza(1, "gads:rtb_v1_1:cld:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcrb = zzaba.zza(1, "gads:rtb_v1_1:cld:check_regex:enabled", (Boolean) true);
    public static final zzaba<String> zzcrc = zzaba.zza(1, "gads:rtb_logging:regex", "(?!)");
    public static final zzaba<Boolean> zzcrd = zzaba.zza(1, "gads:presentation_error:urls_enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcre = zzaba.zza(1, "gads:rtb_interstitial:use_fullscreen_monitor", (Boolean) false);
    public static final zzaba<Boolean> zzcrf = zzaba.zza(1, "gads:native_required_assets:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcrg = zzaba.zza(1, "gads:native_required_assets:check_inner_mediaview:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcrh = zzaba.zza(1, "gads:track_view_next_runloop:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcri = zzaba.zza(1, "gads:v1_1:adapter_initialization:enabled", (Boolean) true);
    public static final zzaba<Integer> zzcrj = zzaba.zza(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    public static final zzaba<Long> zzcrk = zzaba.zzb(1, "gads:adapter_initialization:timeout", 30);
    public static final zzaba<Long> zzcrl = zzaba.zzb(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final zzaba<Boolean> zzcrm = zzaba.zza(1, "gads:additional_video_csi:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcrn = zzaba.zza(1, "gads:csi:enabled_per_sampling", (Boolean) false);
    public static final zzaba<Boolean> zzcro = zzaba.zza(1, "gads:initialization_csi:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcrp = zzaba.zza(1, "gads:initialization_csi_control:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcrq = zzaba.zza(1, "gads:msa:experiments:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcrr = zzaba.zza(1, "gads:msa:experiments:ps:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcrs = zzaba.zza(1, "gads:msa:experiments:fb:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcrt = zzaba.zza(1, "gads:msa:experiments:ps:er", (Boolean) true);
    public static final zzaba<Integer> zzcru = zzaba.zza(1, "gads:gestures:a2:enabled", 0);
    public static final zzaba<Boolean> zzcrv = zzaba.zza(1, "gads:gestures:clearTd:enabled", (Boolean) false);
    public static final zzacx<Boolean> zzcrw = zzadk.zzded;
    public static final zzaba<Boolean> zzcrx = zzaba.zza(1, "gads:gestures:errorlogging:enabled", (Boolean) false);
    public static final zzaba<Long> zzcry = zzaba.zzb(1, "gads:gestures:task_timeout", 2000);
    public static final zzaba<Boolean> zzcrz = zzaba.zza(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcsa = zzaba.zza(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcsb = zzaba.zza(1, "gads:gestures:tos:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcsc = zzaba.zza(1, "gads:gestures:brt:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcsd = zzaba.zza(1, "gads:gestures:fpi:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcse = zzaba.zza(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final zzaba<Boolean> zzcsf = zzaba.zza(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final zzaba<String> zzcsg = zzaba.zza(1, "gads:gestures:pk", "");
    public static final zzaba<Boolean> zzcsh = zzaba.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcsi = zzaba.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcsj = zzaba.zza(1, "gads:gestures:init_new_thread:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcsk = zzaba.zza(1, "gads:gestures:pds:enabled", (Boolean) true);
    private static final zzaba<Integer> zzcsl = zzaba.zza(1, "gads:gestures:as2percentage", 0);
    public static final zzaba<Boolean> zzcsm = zzaba.zza(1, "gads:gestures:ns:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcsn = zzaba.zza(1, "gads:gestures:vdd:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcso = zzaba.zza(1, "gads:native:asset_view_touch_events", (Boolean) false);
    public static final zzaba<Boolean> zzcsp = zzaba.zza(1, "gads:native:set_touch_listener_on_asset_views", (Boolean) true);
    public static final zzaba<Boolean> zzcsq = zzaba.zza(1, "gads:ais:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcsr = zzaba.zza(1, "gads:stav:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcss = zzaba.zza(1, "gads:send_available_disk_space:enabled", (Boolean) false);
    public static final zzaba<String> zzcsu = zzaba.zza(1, "gads:sdk_core_constants:caps", "");
    private static final zzaba<Boolean> zzcsv = zzaba.zza(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final zzaba<String> zzcsw = zzaba.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzaba<String> zzcsx = zzaba.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzaba<String> zzcsy = zzaba.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzaba<Boolean> zzcsz = zzaba.zza(1, "gads:native:get_native_ad_view_signals", (Boolean) false);
    public static final zzaba<Integer> zzcta = zzaba.zza(1, "gads:native_video_load_timeout", 10);
    private static final zzaba<Integer> zzctb = zzaba.zza(1, "gads:omid:native_webview_load_timeout", (int) AdError.SERVER_ERROR_CODE);
    public static final zzaba<Boolean> zzctc = zzaba.zza(1, "gads:omid:native_video_ad_user_action_event:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzctd = zzaba.zza(1, "gads:enable_native_media_aspect_ratio", (Boolean) true);
    public static final zzaba<Boolean> zzcte = zzaba.zza(1, "gads:native:media_content_main_image:enabled", (Boolean) true);
    public static final zzaba<String> zzctf = zzaba.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    private static final zzaba<Boolean> zzctg = zzaba.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzaba<Boolean> zzcth = zzaba.zza(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final zzaba<Boolean> zzcti = zzaba.zza(1, "gads:native:media_view_match_parent:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzctj = zzaba.zza(1, "gads:native:count_impression_for_assets", (Boolean) false);
    private static final zzaba<Boolean> zzctk = zzaba.zza(1, "gads:instream_ad:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzctl = zzaba.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    private static final zzaba<Boolean> zzctm = zzaba.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final zzaba<String> zzctn = zzaba.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static final zzaba<Long> zzcto = zzaba.zzb(1, "gads:auto_location_timeout", 2000);
    private static final zzaba<String> zzctp = zzaba.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static final zzaba<Long> zzctq = zzaba.zzb(1, "gads:auto_location_interval", -1);
    private static final zzaba<String> zzctr = zzaba.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzaba<Boolean> zzcts = zzaba.zza(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzctt = zzaba.zza(1, "gads:get_request_signals_cld:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzctu = zzaba.zza(1, "gads:get_request_signals_common_cld:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzctv = zzaba.zza(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", (Boolean) true);
    public static final zzaba<Long> zzctw = zzaba.zzb(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzaba<Long> zzctx = zzaba.zzb(1, "gads:parental_controls:timeout", 2000);
    private static final zzaba<Integer> zzcty = zzaba.zza(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final zzaba<Integer> zzctz = zzaba.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzaba<Boolean> zzcua = zzaba.zza(1, "gads:cache:downloader_use_high_priority", (Boolean) false);
    private static final zzaba<Long> zzcub = zzaba.zzb(1, "gads:cache:javascript_timeout_millis", ApplicationConstants.CALL_WIDGET_TOOLTIP_HIDE_DELAY);
    public static final zzaba<Boolean> zzcuc = zzaba.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzaba<Boolean> zzcud = zzaba.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzaba<Boolean> zzcue = zzaba.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzaba<Long> zzcuf = zzaba.zzb(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzaba<Boolean> zzcug = zzaba.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final zzaba<Boolean> zzcuh = zzaba.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    public static final zzaba<Long> zzcui = zzaba.zzb(1, "gads:cache:connection_timeout", ApplicationConstants.CALL_WIDGET_TOOLTIP_HIDE_DELAY);
    public static final zzaba<Long> zzcuj = zzaba.zzb(1, "gads:cache:read_only_connection_timeout", ApplicationConstants.CALL_WIDGET_TOOLTIP_HIDE_DELAY);
    public static final zzaba<Boolean> zzcuk = zzaba.zza(1, "gads:cache:read_inner_data_source_if_gcache_miss", (Boolean) false);
    public static final zzaba<Boolean> zzcul = zzaba.zza(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", (Boolean) false);
    public static final zzaba<Boolean> zzcum = zzaba.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzaba<String> zzcun = zzaba.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzaba<Integer> zzcuo = zzaba.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzaba<Boolean> zzcup = zzaba.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcuq = zzaba.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzaba<Boolean> zzcur = zzaba.zza(1, "gads:chrome_custom_tabs_browser_v2:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcus = zzaba.zza(1, "gads:cct_v2_connection:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcut = zzaba.zza(1, "gads:cct_v2_direct_launch:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcuu = zzaba.zza(1, "gads:chrome_custom_tabs_for_native_ads:enabled", (Boolean) false);
    public static final zzaba<Long> zzcuv = zzaba.zzb(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final zzaba<String> zzcuw = zzaba.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzaba<String> zzcux = zzaba.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzaba<String> zzcuy = zzaba.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzaba<String> zzcuz = zzaba.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzaba<Integer> zzcva = zzaba.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzaba<Integer> zzcvb = zzaba.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzaba<Boolean> zzcvc = zzaba.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzaba<Boolean> zzcvd = zzaba.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzaba<Boolean> zzcve = zzaba.zza(1, "gad:interstitial_multi_window_method", (Boolean) false);
    public static final zzaba<Integer> zzcvf = zzaba.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzaba<Boolean> zzcvg = zzaba.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcvh = zzaba.zza(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final zzaba<Boolean> zzcvi = zzaba.zza(1, "gad:publisher_testing:force_local_request:enabled", (Boolean) true);
    public static final zzaba<String> zzcvj = zzaba.zza(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    public static final zzaba<String> zzcvk = zzaba.zza(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    public static final zzaba<Integer> zzcvl = zzaba.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzaba<Boolean> zzcvm = zzaba.zza(1, "gads:omid:enabled", (Boolean) true);
    public static final zzaba<Integer> zzcvn = zzaba.zza(1, "gads:omid:destroy_webview_delay", 1000);
    private static final zzaba<Boolean> zzcvo = zzaba.zza(1, "gads:omid_1_3_activate:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcvp = zzaba.zza(1, "gads:omid_1_3_create_html_session:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcvq = zzaba.zza(1, "gads:omid_1_3_create_js_session:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcvr = zzaba.zza(1, "gads:omid_1_3_friendly_obstruction:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcvs = zzaba.zza(1, "gads:omid_1_3_fire_loaded_event:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcvt = zzaba.zza(1, "gads:nonagon:banner:enabled", (Boolean) true);
    private static final zzaba<String> zzcvu = zzaba.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final zzaba<Boolean> zzcvv = zzaba.zza(1, "gads:nonagon:app_open:enabled", (Boolean) true);
    public static final zzaba<Integer> zzcvw = zzaba.zza(1, "gads:app_open_beta:min_version", 999999999);
    public static final zzaba<Integer> zzcvx = zzaba.zza(1, "gads:app_open_ad_open_beta_api:min_version", 202490999);
    private static final zzaba<String> zzcvy = zzaba.zza(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
    private static final zzaba<Boolean> zzcvz = zzaba.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) true);
    private static final zzaba<String> zzcwa = zzaba.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final zzaba<Boolean> zzcwb = zzaba.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcwc = zzaba.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) true);
    public static final zzaba<String> zzcwd = zzaba.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final zzaba<Boolean> zzcwe = zzaba.zza(1, "gads:nonagon:nativead:enabled", (Boolean) true);
    private static final zzaba<String> zzcwf = zzaba.zza(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final zzaba<Boolean> zzcwg = zzaba.zza(1, "gads:nonagon:banner:check_dp_size", (Boolean) true);
    public static final zzaba<Boolean> zzcwh = zzaba.zza(1, "gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
    private static final zzaba<Boolean> zzcwi = zzaba.zza(1, "gads:nonagon:return_last_error_code", (Boolean) false);
    public static final zzaba<Boolean> zzcwj = zzaba.zza(1, "gads:nonagon:return_no_fill_error_code", (Boolean) false);
    public static final zzaba<Boolean> zzcwk = zzaba.zza(1, "gads:nonagon:continue_on_no_fill", (Boolean) false);
    private static final zzaba<Boolean> zzcwl = zzaba.zza(1, "gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
    public static final zzaba<Boolean> zzcwm = zzaba.zza(1, "gads:nonagon:separate_timeout:enabled", (Boolean) true);
    public static final zzaba<Integer> zzcwn = zzaba.zza(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final zzaba<Boolean> zzcwo = zzaba.zza(1, "gads:nonagon:banner_recursive_renderer", (Boolean) false);
    public static final zzaba<Boolean> zzcwp = zzaba.zza(1, "gads:nonagon:app_stats_lock:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcwq = zzaba.zza(1, "gads:nonagon:app_stats_main_thread:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcwr = zzaba.zza(1, "gads:uri_query_to_map_bg_thread:enabled", (Boolean) false);
    public static final zzaba<String> zzcws = zzaba.zza(1, "gads:uri_query_to_map_bg_thread:types", "/result");
    public static final zzaba<Integer> zzcwt = zzaba.zza(1, "gads:uri_query_to_map_bg_thread:min_length", 1000);
    public static final zzaba<Boolean> zzcwu = zzaba.zza(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcwv = zzaba.zza(1, "gads:active_view_gmsg_separate_pool:enabled", (Boolean) true);
    private static final zzaba<Boolean> zzcww = zzaba.zza(1, "gads:nonagon:service:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcwx = zzaba.zza(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcwy = zzaba.zza(1, "gads:signals:app_index:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcwz = zzaba.zza(1, "gads:signals:attestation_token:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxa = zzaba.zza(1, "gads:signals:cache:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcxb = zzaba.zza(1, "gads:signals:doritos:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxc = zzaba.zza(1, "gads:signals:doritos:v1:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcxd = zzaba.zza(1, "gads:signals:doritos:v2:immediate:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcxe = zzaba.zza(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxf = zzaba.zza(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxg = zzaba.zza(1, "gads:signals:video_decoder:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxh = zzaba.zza(1, "gads:signals:app_version_name:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxi = zzaba.zza(1, "gads:signals:banner_hardware_acceleration:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcxj = zzaba.zza(1, "gads:signals:native_hardware_acceleration:enabled", (Boolean) false);
    private static final zzaba<Boolean> zzcxk = zzaba.zza(1, "gads:attestation_token:enabled", (Boolean) false);
    public static final zzaba<Long> zzcxl = zzaba.zzb(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzaba<Integer> zzcxm = zzaba.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzaba<Integer> zzcxn = zzaba.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
    public static final zzaba<Integer> zzcxo = zzaba.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
    public static final zzaba<Integer> zzcxp = zzaba.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
    private static final zzacx<Boolean> zzcxq = zzadp.zzdel;
    public static final zzaba<Boolean> zzcxr = zzaba.zza(1, "gads:consent:shared_preference_reading:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcxs = zzaba.zza(1, "gads:consent:iab_consent_info:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcxt = zzaba.zza(1, "gads:fc_consent:shared_preference_reading:enabled", (Boolean) true);
    public static final zzaba<String> zzcxu = zzaba.zza(1, "gads:sp:json_string", "");
    public static final zzaba<Boolean> zzcxv = zzaba.zza(1, "gads:nativeads:image:sample:enabled", (Boolean) true);
    public static final zzaba<Integer> zzcxw = zzaba.zza(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final zzaba<Boolean> zzcxx = zzaba.zza(1, "gads:nativeads:pub_image_scale_type:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcxy = zzaba.zza(1, "gads:offline_signaling:enabled", (Boolean) false);
    public static final zzaba<Integer> zzcxz = zzaba.zza(1, "gads:offline_signaling:log_maximum", 100);
    public static final zzaba<Boolean> zzcya = zzaba.zza(1, "gads:nativeads:template_signal:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcyb = zzaba.zza(1, "gads:nativeads:media_content_aspect_ratio:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcyc = zzaba.zza(1, "gads:nativeads:media_content_metadata:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcyd = zzaba.zza(1, "gads:precache_pool:verbose_logging", (Boolean) false);
    public static final zzaba<Integer> zzcye = zzaba.zza(1, "gads:rewarded_precache_pool:count", 0);
    public static final zzaba<Integer> zzcyf = zzaba.zza(1, "gads:interstitial_precache_pool:count", 0);
    public static final zzaba<String> zzcyg = zzaba.zza(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
    public static final zzaba<String> zzcyh = zzaba.zza(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
    public static final zzaba<String> zzcyi = zzaba.zza(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaba<String> zzcyj = zzaba.zza(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaba<Integer> zzcyk = zzaba.zza(1, "gads:rewarded_precache_pool:size", 1);
    public static final zzaba<Integer> zzcyl = zzaba.zza(1, "gads:interstitial_precache_pool:size", 1);
    public static final zzaba<Integer> zzcym = zzaba.zza(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
    public static final zzaba<Integer> zzcyn = zzaba.zza(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
    public static final zzaba<String> zzcyo = zzaba.zza(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaba<String> zzcyp = zzaba.zza(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaba<String> zzcyq = zzaba.zza(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaba<String> zzcyr = zzaba.zza(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
    public static final zzaba<Integer> zzcys = zzaba.zza(1, "gads:app_open_precache_pool:count", 0);
    public static final zzaba<String> zzcyt = zzaba.zza(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaba<Integer> zzcyu = zzaba.zza(1, "gads:app_open_precache_pool:size", 1);
    public static final zzaba<Integer> zzcyv = zzaba.zza(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
    public static final zzaba<Boolean> zzcyw = zzaba.zza(1, "gads:memory_leak:b129558083", (Boolean) false);
    public static final zzaba<Boolean> zzcyx = zzaba.zza(1, "gads:unhandled_event_reporting:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcyy = zzaba.zza(1, "gads:response_info:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzcyz = zzaba.zza(1, "gads:csi:interstitial_failed_to_show:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzcza = zzaba.zza(1, "gads:csi:mediation_failure:enabled", (Boolean) false);
    public static final zzaba<String> zzczb = zzaba.zza(1, "gads:csi:error_parsing:regex", "^(\\d+)");
    public static final zzaba<Boolean> zzczc = zzaba.zza(1, "gads:signal_collection_without_rendering:enabled", (Boolean) true);
    public static final zzaba<Integer> zzczd = zzaba.zza(1, "gads:native_ads_signal:timeout", 1000);
    public static final zzaba<Integer> zzcze = zzaba.zza(1, "gads:signal_v2:min_version", 19677000);
    public static final zzaba<Boolean> zzczf = zzaba.zza(2, "DISABLE_CRASH_REPORTING", (Boolean) false);
    public static final zzaba<Boolean> zzczg = zzaba.zza(1, "gads:paid_event_listener:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczh = zzaba.zza(1, "gads:interscroller_ad:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzczi = zzaba.zza(1, "gads:interscroller_ad:refresh:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczj = zzaba.zza(1, "gads:is_in_scroll_view_new_api:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzczk = zzaba.zza(1, "gads:policy_validator_for_all_pubs:enabled", (Boolean) false);
    public static final zzaba<String> zzczl = zzaba.zza(1, "gad:publisher_testing:policy_validator:enabled_list", "");
    public static final zzaba<Integer> zzczm = zzaba.zza(1, "gads:policy_validator_layoutparam:flags", 808);
    public static final zzaba<Boolean> zzczn = zzaba.zza(2, "NATIVE_AD_DEBUGGER_ENABLED", (Boolean) true);
    public static final zzaba<Integer> zzczo = zzaba.zza(1, "gads:policy_validator_overlay_width:dp", 350);
    public static final zzaba<Integer> zzczp = zzaba.zza(1, "gads:policy_validator_overlay_height:dp", 140);
    public static final zzaba<Boolean> zzczq = zzaba.zza(1, "gads:use_wide_viewport:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczr = zzaba.zza(1, "gads:load_with_overview_mode:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczs = zzaba.zza(1, "gads:wire_banner_listener_after_request:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczt = zzaba.zza(1, "gads:wire_app_open_listener_after_request:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczu = zzaba.zza(1, "gads:wire_interstitial_listener_after_request:enabled", (Boolean) false);
    public static final zzaba<String> zzczv = zzaba.zza(1, "gads:server_transaction_source:list", "Network");
    public static final zzaba<Boolean> zzczw = zzaba.zza(1, "gads:can_open_app_and_open_app_action:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzczx = zzaba.zza(1, "gads:open_gmsg:set_uri_data_and_type:enabled", (Boolean) false);
    public static final zzaba<Integer> zzczy = zzaba.zza(1, "gads:ad_error_api:min_version", 999999999);
    public static final zzaba<Boolean> zzczz = zzaba.zza(1, "gads:forward_bow_error_string:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdaa = zzaba.zza(1, "gads:continue_on_process_response:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdab = zzaba.zza(1, "gads:mediation_status_reporting:enabled", (Boolean) true);
    public static final zzaba<Integer> zzdac = zzaba.zza(1, "gads:mediation_no_fill_error:min_version", 999999999);
    public static final zzaba<Integer> zzdad = zzaba.zza(1, "gads:offline_database_version:version", 1);
    public static final zzaba<Boolean> zzdae = zzaba.zza(1, "gads:offline_ads_notification:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzdaf = zzaba.zza(1, "gads:handle_click_recorded_event:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdag = zzaba.zza(1, "gads:default_network_type_fine_to_unknown:enabled", (Boolean) true);
    public static final zzaba<Boolean> zzdah = zzaba.zza(1, "gads:handle_intent_async:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdai = zzaba.zza(1, "gads:skip_deep_link_validation_native_ads:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdaj = zzaba.zza(1, "gads:try_deep_link_fallback_native_ads:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdak = zzaba.zza(1, "gads:in_app_link_handling_for_android_11_enabled:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdal = zzaba.zza(1, "gads:new_remote_logging_utils:enabled", (Boolean) false);
    public static final zzaba<Boolean> zzdam = zzaba.zza(1, "gads:remote_logging:enabled", (Boolean) false);
    public static final zzaba<Integer> zzdan = zzaba.zza(1, "gads:remote_log_send_rate_ms", 60000);
    public static final zzaba<Integer> zzdao = zzaba.zza(1, "gads:remote_log_queue_max_entries", 500);
    public static final zzaba<Integer> zzdap = zzaba.zza(1, "gads:app_event_queue_size", 20);

    static {
        zzaba<String> zza = zzaba.zza(1, "gads:sdk_core_constants:experiment_id", (String) null);
        zzwr.zzqq().zzb(zza);
        zzcst = zza;
    }

    public static void initialize(Context context) {
        zzbr.zza(new zzdws(context) { // from class: com.google.android.gms.internal.ads.zzabo
            private final Context zzcmi;

            /* JADX INFO: Access modifiers changed from: package-private */
            {
                this.zzcmi = context;
            }

            @Override // com.google.android.gms.internal.ads.zzdws
            public final Object get() {
                return zzwr.zzqr().initialize(this.zzcmi);
            }
        });
    }

    /* JADX WARN: Type inference failed for: r0v4, types: [com.google.android.gms.internal.ads.zzabj, com.google.android.gms.internal.ads.zzadz] */
    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzwr.zzqp();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzadd.zza(new zzabj(zzwr.zzqq(), edit, jSONObject));
        zzwr.zzqq().zza(edit, 1, jSONObject);
        zzwr.zzqp();
        edit.commit();
    }

    public static List<String> zzsc() {
        return zzwr.zzqq().zzsc();
    }

    public static List<String> zzsd() {
        return zzwr.zzqq().zzsd();
    }
}
