package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC2495e;
import com.google.android.gms.common.api.AbstractC2500h;
import com.google.android.gms.common.api.AbstractC2501i;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;
/* renamed from: com.google.android.gms.common.api.internal.al */
/* loaded from: classes-dex2jar.jar:com/google/android/gms/common/api/internal/al.class */
public final class C2516al<R extends AbstractC2500h> extends AbstractC2495e<R> {

    /* renamed from: a */
    private final Status f7095a;

    @Override // com.google.android.gms.common.api.AbstractC2495e
    /* renamed from: a */
    public final R mo14389a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC2495e
    /* renamed from: a */
    public final void mo14388a(AbstractC2495e.AbstractC2496a abstractC2496a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC2495e
    /* renamed from: a */
    public final void mo14387a(AbstractC2501i<? super R> abstractC2501i) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC2495e
    /* renamed from: a */
    public final boolean mo14390a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final Status m14386b() {
        return this.f7095a;
    }
}
