package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC11921j;
import com.google.android.gms.common.api.AbstractC11925m;
import com.google.android.gms.common.api.AbstractC11926n;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.internal.C12045o;
import java.util.concurrent.TimeUnit;
/* renamed from: com.google.android.gms.common.api.internal.ay */
/* loaded from: classes3-dex2jar.jar:com/google/android/gms/common/api/internal/ay.class */
public final class C11857ay<R extends AbstractC11925m> extends AbstractC11921j<R> {

    /* renamed from: a */
    final Status f39265a;

    public C11857ay(Status status) {
        C12045o.m19161a(status, "Status must not be null");
        C12045o.m19153b(!status.isSuccess(), "Status must not be success");
        this.f39265a = status;
    }

    @Override // com.google.android.gms.common.api.AbstractC11921j
    /* renamed from: a */
    public final R mo19293a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC11921j
    /* renamed from: a */
    public final void mo19292a(AbstractC11921j.AbstractC11922a abstractC11922a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC11921j
    /* renamed from: a */
    public final void mo19291a(AbstractC11926n<? super R> abstractC11926n) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
