package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
/* loaded from: classes-dex2jar.jar:com/amazonaws/regions/RegionDefaults.class */
public class RegionDefaults {
    public static List<Region> getRegions() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("ap-northeast-1", "");
        arrayList.add(region);
        updateRegion(region, "s3", "s3-ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "sdb", "sdb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "sqs", "sqs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "ec2", "ec2.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "sns", "sns.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-2", "");
        arrayList.add(region2);
        updateRegion(region2, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "autoscaling", "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "sns", "sns.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "s3", "s3.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "sqs", "sqs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "ec2", "ec2.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "sts", "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region3 = new Region("ap-south-1", "");
        arrayList.add(region3);
        updateRegion(region3, "autoscaling", "autoscaling.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "dynamodb", "dynamodb.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "elasticloadbalancing", "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "ec2", "ec2.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "sns", "sns.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "s3", "s3.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "sqs", "sqs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "sts", "sts.amazonaws.com", false, true);
        Region region4 = new Region("ap-southeast-1", "");
        arrayList.add(region4);
        updateRegion(region4, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "sns", "sns.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "ec2", "ec2.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "sdb", "sdb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "s3", "s3-ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "iot", "iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region4, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "data.iot", "data.iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "sqs", "sqs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "autoscaling", "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-2", "");
        arrayList.add(region5);
        updateRegion(region5, "sqs", "sqs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "iot", "iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "sdb", "sdb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "sns", "sns.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "autoscaling", "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "lambda", "lambda.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "data.iot", "data.iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "dynamodb", "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "ec2", "ec2.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region5, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "s3", "s3-ap-southeast-2.amazonaws.com", false, true);
        Region region6 = new Region("ca-central-1", "");
        arrayList.add(region6);
        updateRegion(region6, "autoscaling", "autoscaling.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "ec2", "ec2.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "sqs", "sqs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region6, "elasticloadbalancing", "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "s3", "s3.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "sns", "sns.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, "dynamodb", "dynamodb.ca-central-1.amazonaws.com", false, true);
        Region region7 = new Region("eu-central-1", "");
        arrayList.add(region7);
        updateRegion(region7, "sqs", "sqs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "data.iot", "data.iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "elasticloadbalancing", "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "iot", "iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "lambda", "lambda.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region7, "sns", "sns.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "dynamodb", "dynamodb.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "s3", "s3.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "autoscaling", "autoscaling.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, "ec2", "ec2.eu-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-west-1", "");
        arrayList.add(region8);
        updateRegion(region8, "sdb", "sdb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "polly", "polly.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "elasticloadbalancing", "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "iot", "iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "sqs", "sqs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "ec2", "ec2.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "data.iot", "data.iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "sns", "sns.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region8, "autoscaling", "autoscaling.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "s3", "s3-eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "dynamodb", "dynamodb.eu-west-1.amazonaws.com", false, true);
        Region region9 = new Region("eu-west-2", "");
        arrayList.add(region9);
        updateRegion(region9, "autoscaling", "autoscaling.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "kinesis", "kinesis.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "sqs", "sqs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region9, "s3", "s3.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "elasticloadbalancing", "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "dynamodb", "dynamodb.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "kms", "kms.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "sns", "sns.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, "ec2", "ec2.eu-west-2.amazonaws.com", false, true);
        Region region10 = new Region("sa-east-1", "");
        arrayList.add(region10);
        updateRegion(region10, "sdb", "sdb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "kinesis", "kinesis.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "sns", "sns.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "autoscaling", "autoscaling.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "elasticloadbalancing", "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "ec2", "ec2.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "s3", "s3-sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region10, "sqs", "sqs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "dynamodb", "dynamodb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region10, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        Region region11 = new Region("us-east-1", "");
        arrayList.add(region11);
        updateRegion(region11, "dynamodb", "dynamodb.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "data.iot", "data.iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "iot", "iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "kms", "kms.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "polly", "polly.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "sqs", "sqs.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region11, "ec2", "ec2.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "elasticloadbalancing", "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "autoscaling", "autoscaling.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "s3", "s3.amazonaws.com", false, true);
        updateRegion(region11, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region11, "sdb", "sdb.amazonaws.com", false, true);
        updateRegion(region11, "sns", "sns.us-east-1.amazonaws.com", false, true);
        Region region12 = new Region("us-east-2", "");
        arrayList.add(region12);
        updateRegion(region12, "elasticloadbalancing", "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "ec2", "ec2.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "sns", "sns.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "kinesis", "kinesis.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "dynamodb", "dynamodb.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "polly", "polly.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "s3", "s3.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region12, "autoscaling", "autoscaling.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "kms", "kms.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "lambda", "lambda.us-east-2.amazonaws.com", false, true);
        updateRegion(region12, "sqs", "sqs.us-east-2.amazonaws.com", false, true);
        Region region13 = new Region("us-west-1", "");
        arrayList.add(region13);
        updateRegion(region13, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "sqs", "sqs.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region13, "ec2", "ec2.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "lambda", "lambda.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "autoscaling", "autoscaling.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "s3", "s3-us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "sdb", "sdb.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "elasticloadbalancing", "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "sns", "sns.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "kms", "kms.us-west-1.amazonaws.com", false, true);
        updateRegion(region13, "dynamodb", "dynamodb.us-west-1.amazonaws.com", false, true);
        Region region14 = new Region("us-west-2", "");
        arrayList.add(region14);
        updateRegion(region14, "sdb", "sdb.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region14, "ec2", "ec2.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "iot", "iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "s3", "s3-us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "kms", "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "sns", "sns.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "polly", "polly.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "sqs", "sqs.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "data.iot", "data.iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "autoscaling", "autoscaling.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "elasticloadbalancing", "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        updateRegion(region14, "dynamodb", "dynamodb.us-west-2.amazonaws.com", false, true);
        Region region15 = new Region("cn-north-1", "");
        arrayList.add(region15);
        updateRegion(region15, "sts", "sts.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "s3", "s3.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "sqs", "sqs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "dynamodb", "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "sns", "sns.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "autoscaling", "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "ec2", "ec2.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region15, "elasticloadbalancing", "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        Region region16 = new Region("us-gov-west-1", "");
        arrayList.add(region16);
        updateRegion(region16, "ec2", "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "s3", "s3-us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "kms", "kms.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "sqs", "sqs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "elasticloadbalancing", "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "sts", "sts.amazonaws.com", false, true);
        updateRegion(region16, "sns", "sns.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "autoscaling", "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region16, "dynamodb", "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        return arrayList;
    }

    public static void updateRegion(Region region, String str, String str2, boolean z, boolean z2) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(str, str2);
        httpSupport.put(str, Boolean.valueOf(z));
        httpsSupport.put(str, Boolean.valueOf(z2));
    }
}
