package com.callapp.contacts.manager.preferences;

import android.os.Build;
import com.callapp.contacts.activity.analytics.cards.CommunityCard;
import com.callapp.contacts.activity.analytics.ui.AnalyticsDatePickerManager;
import com.callapp.contacts.activity.contact.details.ContactAction;
import com.callapp.contacts.activity.contact.details.PostCallActivity;
import com.callapp.contacts.activity.contact.details.overlay.ContactDetailsOverlayView;
import com.callapp.contacts.activity.contact.details.overlay.DuringCallOverlayView;
import com.callapp.contacts.activity.contact.header.ThemeState;
import com.callapp.contacts.activity.contact.list.CallLogSortType;
import com.callapp.contacts.activity.contact.list.ContactsListActivity;
import com.callapp.contacts.activity.marketplace.ButtonSet;
import com.callapp.contacts.activity.marketplace.DownloaderCardViewHandler;
import com.callapp.contacts.activity.settings.Language;
import com.callapp.contacts.activity.whoViewedMyProfile.WhoViewedMyProfileDataManager;
import com.callapp.contacts.api.helper.backup.BackupIntervalPeriod;
import com.callapp.contacts.api.helper.backup.BackupViaType;
import com.callapp.contacts.manager.BlockManager;
import com.callapp.contacts.manager.phone.PhoneManager;
import com.callapp.contacts.manager.preferences.prefs.ArrayPref;
import com.callapp.contacts.manager.preferences.prefs.BooleanPref;
import com.callapp.contacts.manager.preferences.prefs.CachedPref;
import com.callapp.contacts.manager.preferences.prefs.CountryIsoPref;
import com.callapp.contacts.manager.preferences.prefs.DatePref;
import com.callapp.contacts.manager.preferences.prefs.EnumPref;
import com.callapp.contacts.manager.preferences.prefs.IntegerPref;
import com.callapp.contacts.manager.preferences.prefs.IntegerSetPref;
import com.callapp.contacts.manager.preferences.prefs.JSONDatePref;
import com.callapp.contacts.manager.preferences.prefs.LongArray;
import com.callapp.contacts.manager.preferences.prefs.LongPref;
import com.callapp.contacts.manager.preferences.prefs.LongSetPref;
import com.callapp.contacts.manager.preferences.prefs.PairPref;
import com.callapp.contacts.manager.preferences.prefs.StringPref;
import com.callapp.contacts.manager.sim.SimManager;
import com.callapp.contacts.recorder.enums.RecordConfiguration;
import com.callapp.contacts.util.AppRater;
import com.callapp.contacts.util.DeviceDetector;
import com.callapp.contacts.util.ads.AdUtils;
import java.util.Date;
/* loaded from: classes2-dex2jar.jar:com/callapp/contacts/manager/preferences/Prefs.class */
public interface Prefs {
    public static final EnumPref<RecordConfiguration.METHOD> eO;
    public static final EnumPref<RecordConfiguration.AUDIO_SOURCE> eP;
    public static final EnumPref<RecordConfiguration.FILE_FORMAT> eQ;
    public static final BooleanPref eR;
    public static final IntegerPref eS;
    public static final IntegerPref eT;
    public static final BooleanPref eU;
    public static final BooleanPref eV;
    public static final BooleanPref eW;
    public static final BooleanPref eX;
    public static final BooleanPref eY;
    public static final BooleanPref eZ;
    public static final BooleanPref fA;
    public static final IntegerPref fB;
    public static final IntegerPref fC;
    public static final BooleanPref fD;
    public static final BooleanPref fE;
    public static final LongPref fF;
    public static final IntegerPref fG;
    public static final IntegerPref fH;
    public static final BooleanPref fI;
    public static final StringPref fJ;
    public static final StringPref fK;
    public static final IntegerPref fL;
    public static final BooleanPref fM;
    public static final BooleanPref fN;
    public static final BooleanPref fO;
    public static final BooleanPref fP;
    public static final BooleanPref fQ;
    public static final DatePref fR;
    public static final DatePref fS;
    public static final StringPref fT;
    public static final StringPref fU;
    public static final DatePref fV;
    public static final IntegerPref fW;
    public static final IntegerPref fX;
    public static final IntegerPref fY;
    public static final DatePref fZ;
    public static final BooleanPref fa;
    public static final IntegerPref fb;
    public static final DatePref fc;
    public static final DatePref fd;
    public static final BooleanPref fe;
    public static final BooleanPref ff;
    public static final BooleanPref fg;
    public static final BooleanPref fh;
    public static final BooleanPref fi;
    public static final StringPref fj;
    public static final StringPref fk;
    public static final StringPref fl;
    public static final StringPref fm;
    public static final LongSetPref fn;
    public static final LongPref fo;
    public static final BooleanPref fp;
    public static final BooleanPref fq;
    public static final IntegerPref fr;
    public static final BooleanPref fs;
    public static final BooleanPref ft;
    public static final BooleanPref fu;
    public static final BooleanPref fv;
    public static final IntegerPref fw;
    public static final LongPref fx;
    public static final LongPref fy;
    public static final BooleanPref fz;
    public static final BooleanPref gA;
    public static final BooleanPref gB;
    public static final BooleanPref gC;
    public static final IntegerPref gD;
    public static final IntegerPref gE;
    public static final IntegerPref gF;
    public static final EnumPref<AnalyticsDatePickerManager.DatePicker> gG;
    public static final DatePref gH;
    public static final BooleanPref gI;
    public static final BooleanPref gJ;
    public static final BooleanPref gK;
    public static final BooleanPref gL;
    public static final BooleanPref gM;
    public static final BooleanPref gN;
    public static final BooleanPref gO;
    public static final EnumPref<CommunityCard.CommunityContributionLevel> gP;
    public static final BooleanPref gQ;
    public static final IntegerPref gR;
    public static final IntegerPref gS;
    public static final StringPref[] gT;
    public static final BooleanPref gU;
    public static final BooleanPref gV;
    public static final BooleanPref gW;
    public static final IntegerPref gX;
    public static final IntegerPref gY;
    public static final IntegerPref gZ;
    public static final BooleanPref ga;
    public static final LongArray gb;
    public static final BooleanPref gc;
    public static final BooleanPref gd;
    public static final IntegerPref ge;
    public static final BooleanPref gf;
    public static final IntegerPref gg;
    public static final BooleanPref gh;
    public static final LongArray gi;
    public static final BooleanPref gj;
    public static final BooleanPref gk;
    public static final BooleanPref gl;
    public static final BooleanPref gm;
    public static final BooleanPref gn;
    public static final BooleanPref go;
    public static final DatePref gp;
    public static final DatePref gq;
    public static final BooleanPref gr;
    public static final BooleanPref gs;
    public static final BooleanPref gt;
    public static final BooleanPref gu;
    public static final StringPref gv;
    public static final BooleanPref gw;
    public static final BooleanPref gx;
    public static final BooleanPref gy;
    public static final BooleanPref gz;
    public static final BooleanPref hA;
    public static final IntegerPref hB;
    public static final DatePref hC;
    public static final LongPref hD;
    public static final BooleanPref hE;
    public static final BooleanPref hF;
    public static final StringPref hG;
    public static final StringPref hH;
    public static final BooleanPref hI;
    public static final DatePref hJ;
    public static final EnumPref<BackupViaType> hK;
    public static final IntegerPref hL;
    public static final BooleanPref hM;
    public static final BooleanPref hN;
    public static final BooleanPref hO;
    public static final BooleanPref hP;
    public static final BooleanPref hQ;
    public static final BooleanPref hR;
    public static final BooleanPref hS;
    public static final IntegerPref hT;
    public static final BooleanPref hU;
    public static final BooleanPref hV;
    public static final ArrayPref hW;
    public static final DatePref hX;
    public static final DatePref hY;
    public static final DatePref hZ;
    public static final IntegerPref ha;
    public static final BooleanPref hb;
    public static final BooleanPref hc;
    public static final StringPref hd;
    public static final LongPref he;
    public static final StringPref hf;
    public static final IntegerPref hg;
    public static final IntegerPref hh;
    public static final IntegerPref hi;
    public static final BooleanPref hj;
    public static final IntegerPref hk;
    public static final EnumPref<ContactAction> hl;
    public static final IntegerPref hm;
    public static final IntegerPref hn;
    public static final IntegerPref ho;
    public static final IntegerPref hp;
    public static final BooleanPref hq;
    public static final StringPref hr;
    public static final IntegerPref hs;
    public static final IntegerPref ht;
    public static final BooleanPref hu;
    public static final IntegerPref hv;
    public static final BooleanPref hw;
    public static final BooleanPref hx;
    public static final EnumPref<WhoViewedMyProfileDataManager.NotificationWhoViewedMyProfile> hy;
    public static final BooleanPref hz;
    public static final DatePref ia;
    public static final DatePref ib;
    public static final BooleanPref ic;
    public static final BooleanPref id;
    public static final BooleanPref ie;

    /* renamed from: a  reason: collision with root package name */
    public static final BooleanPref f15233a = new BooleanPref("quickSmsEnabled", Boolean.FALSE);

    /* renamed from: b  reason: collision with root package name */
    public static final BooleanPref f15234b = new BooleanPref("dialTonesEnabled", Boolean.TRUE);

    /* renamed from: c  reason: collision with root package name */
    public static final BooleanPref f15235c = new BooleanPref("speakNameEnabled", Boolean.FALSE);

    /* renamed from: d  reason: collision with root package name */
    public static final BooleanPref f15236d = new BooleanPref("vibrateOnClickEnabled", Boolean.TRUE);
    public static final IntegerPref e = new IntegerPref("callsMadeWithoutUsingAsDefaultAppCounter", 0);
    public static final IntegerPref f = new IntegerPref("defaultDailderDialogCounter", 0);
    public static final BooleanPref g = new BooleanPref("inCallFloatingWidgetEnabled", Boolean.TRUE);
    public static final BooleanPref h = new BooleanPref("forcePhoneToRing", Boolean.FALSE);
    public static final BooleanPref i = new BooleanPref("preferPhotosFromDevice", Boolean.FALSE);
    public static final BooleanPref j = new BooleanPref("postCallScreenEnabled", Boolean.TRUE);
    public static final BooleanPref k = new BooleanPref("callFabEnabled", Boolean.TRUE);
    public static final BooleanPref l = new BooleanPref("clipboardAutoSearchEnabled", Boolean.TRUE);
    public static final BooleanPref m = new BooleanPref("incomingSmsEnabled", Boolean.TRUE);
    public static final CachedPref<Boolean> n = new CachedPref<>(new BooleanPref("debugMode", Boolean.FALSE));
    public static final BooleanPref o = new BooleanPref("smsDumpThread", Boolean.FALSE);
    public static final BooleanPref p = new BooleanPref("ignoreImNotificationRules", Boolean.FALSE);
    public static final BooleanPref q = new BooleanPref("showToastIncomingCall", Boolean.FALSE);
    public static final BooleanPref r = new BooleanPref("verifiedSuccess", Boolean.FALSE);
    public static final BooleanPref s = new BooleanPref("verifiedFailed", Boolean.FALSE);
    public static final BooleanPref t = new BooleanPref("contactListPageSwipeEnabled", Boolean.TRUE);
    public static final PairPref<Integer, Integer> u = new PairPref<>(new IntegerPref("birthdayReminderTimeHours"), new IntegerPref("birthdayReminderTimeMinutes"));
    public static final PairPref<Long, String> v = new PairPref<>(new LongPref("clipTimeStampMillis"), new StringPref("clipText"));
    public static final BooleanPref w = new BooleanPref("historyFragmentShouldConfirmDelete", Boolean.TRUE);
    public static final BooleanPref x = new BooleanPref("birthdayReminderSoundEnabled", Boolean.TRUE);
    public static final BooleanPref y = new BooleanPref("missedCallCardEnabled", Boolean.TRUE);
    public static final BooleanPref z = new BooleanPref("notAnsweredCardEnabled", Boolean.TRUE);
    public static final BooleanPref A = new BooleanPref("missedCallOverlayEnabled", Boolean.TRUE);
    public static final BooleanPref B = new BooleanPref("notAnsweredOverlayEnabled", Boolean.TRUE);
    public static final BooleanPref C = new BooleanPref("missedCallDailySummaryEnabled", Boolean.TRUE);
    public static final BooleanPref D = new BooleanPref("notAnswerDailySummaryEnabled", Boolean.TRUE);
    public static final BooleanPref E = new BooleanPref("notAnswerNotificationEnabled", Boolean.TRUE);
    public static final BooleanPref F = new BooleanPref("missedCallNotificationEnabled", Boolean.TRUE);
    public static final BooleanPref G = new BooleanPref("callAppPlusDailySummaryEnabled", Boolean.TRUE);
    public static final LongPref H = new LongPref("lastMissedCallTimeOverlay", 0L);
    public static final LongPref I = new LongPref("lastNotAnsweredTimeOverlay", 0L);
    public static final BooleanPref J = new BooleanPref("hasPendingMissedCallDailySummary", Boolean.FALSE);
    public static final BooleanPref K = new BooleanPref("hasPendingNotAnswerDailySummary", Boolean.FALSE);
    public static final BooleanPref L = new BooleanPref("missedCallAnimationEnabled", Boolean.TRUE);
    public static final DatePref M = new DatePref("missedCallSummaryLastScheduled", null);
    public static final IntegerPref N = new IntegerPref("overlayViewYPos", Integer.valueOf((int) DuringCallOverlayView.OVERLAY_Y_POS_DEFAULT_VALUE));
    public static final IntegerPref O = new IntegerPref("callOverlaySeenCount", 0);
    public static final BooleanPref P = new BooleanPref("wasCallOverlaySwiped", Boolean.FALSE);
    public static final BooleanPref Q = new BooleanPref("wasCallOverlayMoved", Boolean.FALSE);
    public static final IntegerPref R = new IntegerPref("installedVersionCode");
    public static final IntegerPref S = new IntegerPref("lastOsVersion", 0);
    public static final IntegerPref T = new IntegerPref("lastVersionCode", 0);
    public static final IntegerPref U = new IntegerPref("birthdayReminderBaseId", 100);
    public static final IntegerPref V = new IntegerPref("notificationReminderBaseId", 10000);
    public static final BooleanPref W = new BooleanPref("shortcutCreated", Boolean.FALSE);
    public static final StringPref X = new StringPref("installationReferrer");
    public static final IntegerPref Y = new IntegerPref("numTimesRateScreenShown", 0);
    public static final LongPref Z = new LongPref("rateUsDifferentIdentifiesCounter", 0L);
    public static final StringPref aa = new StringPref("rateUsLastIdentifyNumber", (String) null);
    public static final LongPref ab = new LongPref("rateUsLastIdentifyDates", 0L);
    public static final DatePref ac = new DatePref("lastServerMessageShownTime");
    public static final DatePref ad = new DatePref("showUpdrageNotificationFirstTimeDate");
    public static final DatePref ae = new DatePref("lastMissedCallProcessedTimestamp", new Date());
    public static final DatePref af = new DatePref("lastNotAnsweredProcessedTimestamp", new Date());
    public static final BooleanPref ag = new BooleanPref("hasMessageInCallLog", Boolean.TRUE);
    public static final DatePref ah = new DatePref("installDate", null);
    public static final DatePref ai = new DatePref("lastUpgradeDate", null);
    public static final LongPref aj = new LongPref("lastRegisterOnServer", 0L);
    public static final EnumPref<AppRater.UserRating> ak = new EnumPref<>("userRating", AppRater.UserRating.NOT_YET);
    public static final BooleanPref al = new BooleanPref("isAlreadyGetFavorites", Boolean.FALSE);
    public static final IntegerPref am = new IntegerPref("notificationChannelPrefix", 0);
    public static final DatePref an = new DatePref("lastTimeUserWasShownLoyaltyRipple", null);
    public static final StringPref ao = new StringPref("normalNumbers");
    public static final StringPref ap = new StringPref("areaCode");
    public static final StringPref aq = new StringPref("email");
    public static final StringPref ar = new StringPref("firstName");
    public static final StringPref as = new StringPref("lastName");
    public static final StringPref at = new StringPref("bio");
    public static final StringPref au = new StringPref("address");
    public static final StringPref av = new StringPref("userDefinition");
    public static final StringPref[] aw = {new StringPref("userWebsite1", (String) null), new StringPref("userWebsite2", (String) null), new StringPref("userWebsite3", (String) null), new StringPref("userWebsite4", (String) null)};
    public static final StringPref[] ax = {new StringPref("userEmail1", (String) null), new StringPref("userEmail2", (String) null), new StringPref("userEmail3", (String) null), new StringPref("userEmail4", (String) null)};
    public static final BooleanPref ay = new BooleanPref("copyUserDeviceEmailsToOurData", Boolean.TRUE);
    public static final DatePref az = new DatePref("birthDate", null);
    public static final JSONDatePref aA = new JSONDatePref("birthDateFormatted", null);
    public static final StringPref aB = new StringPref("userYoutubeChannel", (String) null);
    public static final StringPref aC = new StringPref("userDeletedEmails", (String) null);
    public static final StringPref aD = new StringPref("userDeletedWebsites", (String) null);
    public static final ArrayPref aE = new ArrayPref("speedDial");
    public static final StringPref aF = new StringPref("verifiedPhoneWithDigits");
    public static final PairPref<String, String> aG = new PairPref<>(new StringPref("twitterAccessToken"), new StringPref("twitterAccessTokenSecret"));
    public static final StringPref aH = new StringPref("googlePlusAccountName");
    public static final DatePref aI = new DatePref("googlePlusAccountIdTimeStamp", new Date());
    public static final BooleanPref aJ = new BooleanPref("googlePlusUseOldPermissions", Boolean.FALSE);
    public static final StringPref aK = new StringPref("gmailAccountName");
    public static final BooleanPref aL = new BooleanPref("callAppAsPremiumFlow", Boolean.TRUE);
    public static final DatePref aM = new DatePref("callAppAsPremiumFlowStartTime", null);
    public static final BooleanPref aN = new BooleanPref("shownPostTrialTimePremiumPopUp", Boolean.FALSE);
    public static final BooleanPref aO = new BooleanPref("shown2DaysReminderPremiumPopUp", Boolean.FALSE);
    public static final CountryIsoPref aP = new CountryIsoPref("countryIso");
    public static final StringPref aQ = new StringPref("unreliableCountryIso");
    public static final StringPref aR = new StringPref("callAppId");
    public static final BooleanPref aS = new BooleanPref("numberIsReliable", Boolean.FALSE);
    public static final BooleanPref aT = new BooleanPref("numberVerified", Boolean.FALSE);
    public static final IntegerPref aU = new IntegerPref("setupStage", 0);
    public static final StringPref aV = new StringPref("activationCode");
    public static final BooleanPref aW = new BooleanPref("setupCompleted", Boolean.FALSE);
    public static final StringPref aX = new StringPref("registrationMethod");
    public static final BooleanPref aY = new BooleanPref("userOnPayWallOnBoardingPayment", Boolean.FALSE);
    public static final BooleanPref aZ = new BooleanPref("shouldUpdateRemoteConfigDefualts", Boolean.TRUE);
    public static final BooleanPref ba = new BooleanPref("shouldForceFetchRemoteConfig", Boolean.FALSE);
    public static final BooleanPref bb = new BooleanPref("shouldShowWhatsNew", Boolean.TRUE);
    public static final EnumPref<AdUtils.ConsentStatus> bc = new EnumPref<>("gdprConsentStatus", AdUtils.ConsentStatus.UNKNOWN);
    public static final IntegerPref bd = new IntegerPref("tcf2ConsentShownCount", 0);
    public static final DatePref be = new DatePref("tcf2ConsentNextShow", null);
    public static final BooleanPref bf = new BooleanPref("tcf2ConsentForce", Boolean.FALSE);
    public static final BooleanPref bg = new BooleanPref("privacyConsentStatus", Boolean.FALSE);
    public static final BooleanPref bh = new BooleanPref("dateFormatMonthFirst", null);
    public static final StringPref[] bi = {new StringPref("quickSms1", 2131886715), new StringPref("quickSms2", 2131886716), new StringPref("quickSms3", 2131886717), new StringPref("quickSms4", 2131886718)};
    public static final BooleanPref[] bj = {new BooleanPref("quickSms1Changes", Boolean.FALSE), new BooleanPref("quickSms2Changes", Boolean.FALSE), new BooleanPref("quickSms3Changes", Boolean.FALSE), new BooleanPref("quickSms4Changes", Boolean.FALSE)};
    public static final BooleanPref bk = new BooleanPref("showCallAppOnIncoming", Boolean.TRUE);
    public static final BooleanPref bl = new BooleanPref("showCallAppOnOutgoing", Boolean.TRUE);
    public static final BooleanPref bm = new BooleanPref("fullScreenModeEnabled", Boolean.TRUE);
    public static final BooleanPref bn = new BooleanPref("isFirstSyncFinished", Boolean.FALSE);
    public static final IntegerPref bo = new IntegerPref("totalContactsToSync", 0);
    public static final IntegerPref bp = new IntegerPref("indexOfIteratedContactsFirstSync", 0);
    public static final DatePref bq = new DatePref("firstSyncStartTime");
    public static final DatePref br = new DatePref("firstSyncEndTime");
    public static final LongPref bs = new LongPref("firstSyncTotalTimeInSecs");
    public static final IntegerPref bt = new IntegerPref("batteryStartSync");
    public static final IntegerPref bu = new IntegerPref("batteryEndSync");
    public static final DatePref bv = new DatePref("fullSyncEndTime");
    public static final IntegerSetPref bw = new IntegerSetPref("socialNetIdThatAlreadyClikedOnSocialProfileScreen");
    public static final StringPref bx = new StringPref("menuLangauge", "system_locale");
    public static final IntegerPref by = new IntegerPref("numOfCallsSinceStartedRegistration", 0);
    public static final IntegerPref bz = new IntegerPref("numOfBotherTheUserWithRegistration", 0);
    public static final EnumPref<Language> bA = new EnumPref<>("t9Language", Language.NONE);
    public static final BooleanPref bB = new BooleanPref("sawRegistrationReminderNotification", Boolean.FALSE);
    public static final IntegerPref bC = new IntegerPref("abTestUserId");
    public static final BooleanPref bD = new BooleanPref("shouldAskUserForExtraLanguage", null);
    public static final IntegerPref bE = new IntegerPref("locationPermissionInSearchCounter", 4);
    public static final DatePref bF = new DatePref("lastTimeSmsPermissionRequestWasShown", new Date());
    public static final IntegerPref bG = new IntegerPref("smsPermissionDisplayedFromReminderCounter", 0);
    public static final IntegerPref bH = new IntegerPref("smsPermissionCallAppPlusCounter", 0);
    public static final IntegerPref bI = new IntegerPref("callappPlusOpenedCounter", 0);
    public static final BooleanPref bJ = new BooleanPref("privateCall", Boolean.FALSE);
    public static final BooleanPref bK = new BooleanPref("internationalCall", Boolean.FALSE);
    public static final BooleanPref bL = new BooleanPref("nonContactCall", Boolean.FALSE);
    public static final EnumPref<BlockManager.BlockMethod> bM = new EnumPref<>("blockMethodType", BlockManager.BlockMethod.HANG_UP);
    public static final BooleanPref bN = new BooleanPref("commonSpammers", Boolean.TRUE);
    public static final EnumPref<ContactDetailsOverlayView.InCallDuration> bO = new EnumPref<>("inCallDuration", ContactDetailsOverlayView.InCallDuration.NEVER);
    public static final EnumPref<PostCallActivity.PostCallDuration> bP = new EnumPref<>("postCallDuration", PostCallActivity.PostCallDuration.AFTER_5_SEC);
    public static final EnumPref<PostCallActivity.PostCallDuration> bQ = new EnumPref<>("clipboardAutoSearchDuration", PostCallActivity.PostCallDuration.AFTER_12_SEC);
    public static final EnumPref<SimManager.SimId> bR = new EnumPref<>("simId", SimManager.SimId.ASK);
    public static final StringPref bS = new StringPref("simIdColumnsName", (String) null);
    public static final StringPref bT = new StringPref("phoneManagerClassName", (String) null);
    public static final StringPref bU = new StringPref("voiceMailAsGlobal", (String) null);
    public static final IntegerPref bV = new IntegerPref("callReminderAddedCounter", 0);
    public static final DatePref bW = new DatePref("lastImProcessedTimestamp", new Date());
    public static final IntegerPref bX = new IntegerPref("missedCallNotificationClickedCounter", 0);
    public static final BooleanPref bY = new BooleanPref("hasSendEventUserAllowedUsNotificationAccess", Boolean.FALSE);
    public static final LongPref bZ = new LongPref("seenContactDetailsCounter", 0L);
    public static final BooleanPref ca = new BooleanPref("userLongPressedCallFab", Boolean.FALSE);
    public static final IntegerPref cb = new IntegerPref("userOpenDetailScreenCount", -1);
    public static final BooleanPref cc = new BooleanPref("shownAutoStartPermissionPusher", Boolean.FALSE);
    public static final BooleanPref cd = new BooleanPref("shownHuaweiProtectedAppsPusher", Boolean.FALSE);
    public static final BooleanPref ce = new BooleanPref("showCallAppIMNotification", Boolean.TRUE);
    public static final BooleanPref cf = new BooleanPref("showCallAppSpamAndBlockNotification", Boolean.TRUE);
    public static final BooleanPref cg = new BooleanPref("isViberSenderNameOK", Boolean.TRUE);
    public static final BooleanPref ch = new BooleanPref("isTelegramSenderNameOK", Boolean.TRUE);
    public static final BooleanPref ci = new BooleanPref("isWearableNodeFoundAlreadyReported ", Boolean.FALSE);
    public static final LongPref cj = new LongPref("whatsappUsageCounter", 0L);
    public static final LongPref ck = new LongPref("whatsapp4BUsageCounter", 0L);
    public static final LongPref cl = new LongPref("telegramUsageCounter", 0L);
    public static final LongPref cm = new LongPref("viberUsageCounter", 0L);
    public static final LongPref cn = new LongPref("googlePlusHangoutsUsageCounter", 0L);
    public static final LongPref co = new LongPref("weChatUsageCounter", 0L);
    public static final LongPref cp = new LongPref("skypeUsageCounter", 0L);
    public static final LongPref cq = new LongPref("messengerUsageCounter", 0L);
    public static final LongPref cr = new LongPref("yahooUsageCounter", 0L);
    public static final LongPref cs = new LongPref("emailUsageCounter", 0L);
    public static final LongPref ct = new LongPref("smsUsageCounter", 0L);
    public static final LongPref cu = new LongPref("facebookMessengerUsageCounter", 0L);
    public static final LongPref cv = new LongPref("duoUsageCounter", 0L);
    public static final LongPref cw = new LongPref("signalUsageCounter", 0L);
    public static final LongPref cx = new LongPref("alloUsageCounter", 0L);
    public static final IntegerPref cy = new IntegerPref("smsAdRuleCounter", 0);
    public static final IntegerPref cz = new IntegerPref("adImpressionCounter", 0);
    public static final LongPref cA = new LongPref("seenDifferentContactInCDCounter", 0L);
    public static final StringPref cB = new StringPref("lastContactDetailsPhoneSeen", (String) null);
    public static final DatePref cC = new DatePref("lastAccessRequestPopupSeenOnIdentifiedContactsLogTimestamp", null);
    public static final IntegerPref cD = new IntegerPref("accessRequestPopupSeenOnIdentifiedContactsLogCount", 0);
    public static final BooleanPref cE = new BooleanPref("bottomSheetPlusBtnHasEverPressed", Boolean.FALSE);
    public static final DatePref cF = new DatePref("amountOfCallsTodayDate", new Date());
    public static final IntegerPref cG = new IntegerPref("amountOfCallsToday", 0);
    public static final IntegerPref cH = new IntegerPref("amountOfInterstitialSeenToday", 0);
    public static final BooleanPref cI = new BooleanPref("missedInterstitialOnInterval", Boolean.FALSE);
    public static final BooleanPref cJ = new BooleanPref("isPremium", Boolean.FALSE);
    public static final BooleanPref cK = new BooleanPref("hasFreeStoreSku", Boolean.FALSE);
    public static final BooleanPref cL = new BooleanPref("hasFiveFreeStoreSku", Boolean.FALSE);
    public static final IntegerPref cM = new IntegerPref("fiveSkusCounter", 0);
    public static final DatePref cN = new DatePref("adsFreeGiftEndDate", null);
    public static final IntegerPref cO = new IntegerPref("freeStoreItemCredit", 0);
    public static final BooleanPref cP = new BooleanPref("allStoreFree", Boolean.FALSE);
    public static final BooleanPref cQ = new BooleanPref("needToShowfreeStoreItemCreditDialog", Boolean.TRUE);
    public static final BooleanPref cR = new BooleanPref("needToShowFreeStoreItemCreditDialogInsideContactList", Boolean.FALSE);
    public static final EnumPref<DownloaderCardViewHandler.StoreItemType> cS = new EnumPref<>("freeStoreDialogItemType", DownloaderCardViewHandler.StoreItemType.OTHER);
    public static final IntegerPref cT = new IntegerPref("freeCallScreenItemCredit", 0);
    public static final IntegerPref cU = new IntegerPref("freePersonalCallScreenItemCredit", 0);
    public static final IntegerPref cV = new IntegerPref("freePersonalCoverItemCredit", 0);
    public static final ArrayPref cW = new ArrayPref("storeItemAwardedAsGift");
    public static final BooleanPref cX = new BooleanPref("awardFreeGiftAfterUpgrade", Boolean.FALSE);
    public static final DatePref cY = new DatePref("gotChurnTrueDate", null);
    public static final EnumPref<ContactsListActivity.ContentState> cZ = new EnumPref<>("lastStateInContactList", ContactsListActivity.ContentState.UNSET);
    public static final DatePref da = new DatePref("lastSeenCallLogTimestamp", new Date());
    public static final EnumPref<CallLogSortType> db = new EnumPref<>("calllogSortType", CallLogSortType.SORTED_BY_DATE);
    public static final BooleanPref dc = new BooleanPref("hasClickedBuyOnPremiumPopup", Boolean.FALSE);
    public static final IntegerPref dd = new IntegerPref("buyPremiumPopupSeenCount", 0);
    public static final BooleanPref de = new BooleanPref("isMiuiDevice", null);
    public static final IntegerPref df = new IntegerPref("catalogVersion", 0);
    public static final StringPref dg = new StringPref("theme", "LIGHT");
    public static final StringPref dh = new StringPref("chosenTheme", "default_1");
    public static final EnumPref<ThemeState> di = new EnumPref<>("themeState", ThemeState.WHITE);
    public static final StringPref dj = new StringPref("primaryColor", "#0288D1");
    public static final StringPref dk = new StringPref("primaryColorLight", "#98e3f4");
    public static final StringPref dl = new StringPref("primaryColorDark", "#016CA6");
    public static final StringPref dm = new StringPref("darkPrimaryColor", "#5791aa");
    public static final StringPref dn = new StringPref("darkPrimaryColorLight", "#72b0c1");

    /* renamed from: do  reason: not valid java name */
    public static final StringPref f364do = new StringPref("darkPrimaryColorDark", "#325061");
    public static final StringPref dp = new StringPref("overlayTintColor", "#B3009EFF");
    public static final StringPref[] dq = {new StringPref("overlayChosenCover_1", (String) null), new StringPref("overlayChosenCover_2", (String) null), new StringPref("overlayChosenCover_3", (String) null), new StringPref("overlayChosenCover_4", (String) null), new StringPref("overlayChosenCover_5", (String) null)};
    public static final BooleanPref dr = new BooleanPref("overlayCover", Boolean.TRUE);
    public static final StringPref ds = new StringPref("callScreenThemeUrl", (String) null);
    public static final BooleanPref dt = new BooleanPref("personalCallScreenFirstTime", Boolean.TRUE);
    public static final BooleanPref du = new BooleanPref("isCallScreenSkuPurchased", Boolean.FALSE);
    public static final BooleanPref dv = new BooleanPref("isPersonalCallScreenSkuPurchased", Boolean.FALSE);
    public static final BooleanPref dw = new BooleanPref("isPersonalCallScreenCardClicked", Boolean.FALSE);
    public static final IntegerPref dx = new IntegerPref("personalCallScreenCardShowedNumber", 0);
    public static final EnumPref<ButtonSet> dy = new EnumPref<>("buttonSet", ButtonSet.SINGLE_DEFAULT);
    public static final BooleanPref dz = new BooleanPref("shouldShowCallScreenThemeTooltip", Boolean.TRUE);
    public static final BooleanPref dA = new BooleanPref("isKeypadBannerActive", Boolean.TRUE);
    public static final BooleanPref dB = new BooleanPref("isPersonalCoverSkuPurchased", Boolean.FALSE);
    public static final BooleanPref dC = new BooleanPref("personalCoverScreenFirstTime", Boolean.TRUE);
    public static final DatePref dD = new DatePref("firstShownCallScreenVersion", new Date());
    public static final IntegerPref dE = new IntegerPref("incomingCallsCounter", 0);
    public static final BooleanPref dF = new BooleanPref("shouldDisplayCallScreenThemeFullScreenBanner", Boolean.TRUE);
    public static final StringPref dG = new StringPref("superSkinListLightBackground", (String) null);
    public static final StringPref dH = new StringPref("superSkinListDarkBackground", (String) null);
    public static final StringPref[] dI = {new StringPref("superSkinLightTopBarBackground_1", (String) null), new StringPref("superSkinLightTopBarBackground_2", (String) null), new StringPref("superSkinLightTopBarBackground_3", (String) null), new StringPref("superSkinLightTopBarBackground_4", (String) null), new StringPref("superSkinLightTopBarBackground_5", (String) null)};
    public static final StringPref[] dJ = {new StringPref("superSkinDarkTopBarBackground_1", (String) null), new StringPref("superSkinDarkTopBarBackground_2", (String) null), new StringPref("superSkinDarkTopBarBackground_3", (String) null), new StringPref("superSkinDarkTopBarBackground_4", (String) null), new StringPref("superSkinDarkTopBarBackground_5", (String) null)};
    public static final StringPref dK = new StringPref("superSkinCard", (String) null);
    public static final StringPref dL = new StringPref("superSkinWizardImage", (String) null);
    public static final StringPref dM = new StringPref("superSkinGif", (String) null);
    public static final StringPref dN = new StringPref("chosenCover", (String) null);
    public static final StringPref dO = new StringPref("chosenKeypad", (String) null);
    public static final StringPref dP = new StringPref("chosenCustomKeypadImageUrl", (String) null);
    public static final DatePref dQ = new DatePref("chosenCustomKeypadImageUrlSignature", null);
    public static final DatePref dR = new DatePref("chosenCustomCoverImageUrlSignature", null);
    public static final StringPref dS = new StringPref("chosenKeypadImageUrl", (String) null);
    public static final StringPref[] dT = {new StringPref("cover_1", (String) null), new StringPref("cover_2", (String) null), new StringPref("cover_3", (String) null), new StringPref("cover_4", (String) null), new StringPref("cover_5", (String) null)};
    public static final BooleanPref dU = new BooleanPref("superSkinContactDetailsBackgroundImageEnabled", Boolean.TRUE);
    public static final BooleanPref dV = new BooleanPref("superSkinMainScreenBackgroundImageEnabled", Boolean.TRUE);
    public static final BooleanPref dW = new BooleanPref("superSkinMainScreenTopBarImageEnabled", Boolean.TRUE);
    public static final BooleanPref dX = new BooleanPref("superSkinMainScreenAnimatedWizardEnabled", Boolean.TRUE);
    public static final BooleanPref dY = new BooleanPref("superSkinAppMenuAnimatedWizardEnabled", Boolean.TRUE);
    public static final BooleanPref dZ = new BooleanPref("superSkinEnabled", Boolean.FALSE);
    public static final BooleanPref ea = new BooleanPref("hasPurchasedSuperSkin", Boolean.FALSE);
    public static final BooleanPref eb = new BooleanPref("forcePremium", Boolean.FALSE);
    public static final BooleanPref ec = new BooleanPref("forceInterstitial", Boolean.FALSE);
    public static final BooleanPref ed = new BooleanPref("customizeReportId", Boolean.FALSE);
    public static final IntegerPref ee = new IntegerPref("showCoverHeaderFirstTimeAnimationCounter", 0);
    public static final IntegerPref ef = new IntegerPref("showSuperSkinMoreInfoHeaderFirstTimeAnimationCounter", 0);
    public static final BooleanPref eg = new BooleanPref("isMarketWidgetEnabled", Boolean.FALSE);
    public static final BooleanPref eh = new BooleanPref("shouldShowMarketBadge", Boolean.FALSE);
    public static final IntegerPref ei = new IntegerPref("identifiedContactsLogUnreadDataCount", 0);
    public static final DatePref ej = new DatePref("callRecorderLastShownMessage", null);
    public static final IntegerPref ek = new IntegerPref("identifiedSpammersUnreadDataCount", 0);
    public static final BooleanPref el = new BooleanPref("shouldFlagWhatsNewInSlideMenu", Boolean.TRUE);
    public static final BooleanPref em = new BooleanPref("wakeUpScreenInPostCall", Boolean.FALSE);
    public static final BooleanPref en = new BooleanPref("enableStoreDebugCatalog", Boolean.FALSE);
    public static final BooleanPref eo = new BooleanPref("enableInvitesDebugCatalog", Boolean.FALSE);
    public static final BooleanPref ep = new BooleanPref("showCallLogStickyBanner", Boolean.FALSE);
    public static final BooleanPref eq = new BooleanPref("showCallLogDefaultDialerBanner", Boolean.FALSE);
    public static final BooleanPref er = new BooleanPref("showCallRecorderSticky", Boolean.FALSE);
    public static final BooleanPref es = new BooleanPref("firstTimeExperienceCallLogShowed", Boolean.FALSE);
    public static final BooleanPref et = new BooleanPref("firstTimeExperienceShowContactDetailsTooltip", Boolean.FALSE);
    public static final StringPref[] eu = {new StringPref("contactData_name_1", (String) null), new StringPref("contactData_name_2", (String) null), new StringPref("contactData_name_3", (String) null)};
    public static final StringPref[] ev = {new StringPref("contactData_phone_1", (String) null), new StringPref("contactData_phone_2", (String) null), new StringPref("contactData_phone_3", (String) null)};
    public static final LongPref[] ew = {new LongPref("contactData_device_id_1", -1L), new LongPref("contactData_device_id_2", -1L), new LongPref("contactData_device_id_3", -1L)};
    public static final LongPref[] ex = {new LongPref("contactData_date_1", -1L), new LongPref("contactData_date_2", -1L), new LongPref("contactData_date_3", -1L)};
    public static final IntegerPref[] ey = {new IntegerPref("contactData_call_history_icon_1", -1), new IntegerPref("contactData_call_history_icon_2", -1), new IntegerPref("contactData_call_history_icon_3", -1)};
    public static final StringPref[] ez = {new StringPref("contactData_profile_url_1", (String) null), new StringPref("contactData_profile_url_2", (String) null), new StringPref("contactData_profile_url_3", (String) null)};
    public static final IntegerPref eA = new IntegerPref("promotionVersion", 0);
    public static final LongPref eB = new LongPref("lastKnownLocationTimestamp", -1L);
    public static final StringPref eC = new StringPref("lastKnownLocationParcel", (String) null);
    public static final LongPref eD = new LongPref("thankfulDialogDate", -1L);
    public static final IntegerPref eE = new IntegerPref("seenContactDetailsScreenCount", 0);
    public static final IntegerPref eF = new IntegerPref("seenContactDetailsProfileRippleEffect", 0);
    public static final IntegerPref eG = new IntegerPref("numManualRecordingInitiated", 0);
    public static final BooleanPref eH = new BooleanPref("callRecorderManual", Boolean.TRUE);
    public static final BooleanPref eI = new BooleanPref("callRecorderAuto", Boolean.FALSE);
    public static final BooleanPref eJ = new BooleanPref("callRecorderIncomingCallEnabled", Boolean.FALSE);
    public static final BooleanPref eK = new BooleanPref("callRecorderOutgoingCallEnabled", Boolean.FALSE);
    public static final BooleanPref eL = new BooleanPref("callRecorderAcceptTerms", Boolean.FALSE);
    public static final BooleanPref eM = new BooleanPref("shouldDisplayCallRecordingUpdate", Boolean.TRUE);
    public static final IntegerPref eN = new IntegerPref("callRecorderConfigurations", 1);

    static {
        eO = new EnumPref<>("callRecorderMethod", Build.VERSION.SDK_INT >= 23 ? RecordConfiguration.METHOD.METHOD_NATIVE : RecordConfiguration.METHOD.METHOD_NON_NATIVE);
        eP = new EnumPref<>("callRecorderAudioSource", RecordConfiguration.AUDIO_SOURCE.VOICE_RECOGNITION);
        eQ = new EnumPref<>("callRecorderFileFormat", RecordConfiguration.FILE_FORMAT.AMR);
        eR = new BooleanPref("forceInCommunicationMode", Boolean.valueOf(Build.VERSION.SDK_INT < 28));
        eS = new IntegerPref("callRecorderMaxRecordsValue", 1);
        eT = new IntegerPref("callRecorderIncreaseVolume", 3);
        eU = new BooleanPref("callRecorderNormalizeSpeed", Boolean.FALSE);
        eV = new BooleanPref("callRecorderIsOutgoingCreated", Boolean.FALSE);
        eW = new BooleanPref("callRecorderIsIncomingCreated", Boolean.FALSE);
        eX = new BooleanPref("callRecorderIsEnjoyDialogShowed", Boolean.FALSE);
        eY = new BooleanPref("showAccessibilityServiceAfterUpgrade", Boolean.FALSE);
        eZ = new BooleanPref("gaveAccessibilityOnce", Boolean.FALSE);
        fa = new BooleanPref("gaveDefaultDialerOnce", Boolean.valueOf(PhoneManager.get().isDefaultSystemPhoneApp()));
        fb = new IntegerPref("accessibilityPopupCallCounter", 0);
        fc = new DatePref("accessibilityPopupLastShown", null);
        fd = new DatePref("accessibilityPopupFirstShown", null);
        fe = new BooleanPref("dontRemindAccessibility", Boolean.FALSE);
        ff = new BooleanPref("callRecorderHintLayout", Boolean.TRUE);
        fg = new BooleanPref("blockedSpamHintLayout", Boolean.TRUE);
        fh = new BooleanPref("callAppPlusHintLayout", Boolean.TRUE);
        fi = new BooleanPref("lowDeviceStorage", Boolean.FALSE);
        fj = new StringPref("deeplinkSource");
        fk = new StringPref("deeplinkMedium");
        fl = new StringPref("deeplinkCampaign");
        fm = new StringPref("deeplinkTerm");
        fn = new LongSetPref("identifyContactResult");
        fo = new LongPref("identifyContactLastCheck", -1L);
        fp = new BooleanPref("identifyContactHintVisibility", Boolean.TRUE);
        fq = new BooleanPref("identifyContactShownAfterInstall", Boolean.FALSE);
        fr = new IntegerPref("adsClickCounter", 0);
        fs = new BooleanPref("isFirstSuccessRecordAnalyticsSent", Boolean.FALSE);
        ft = new BooleanPref("shouldSendUserCorrectedExplicitAnalytics", Boolean.TRUE);
        fu = new BooleanPref("seenRecordDialogBefore", Boolean.FALSE);
        fv = new BooleanPref("shouldCheckRunInBGPermissionForNewUsers", Boolean.TRUE);
        fw = new IntegerPref("interstitialCounter", 0);
        fx = new LongPref("lastContactObserverUpdatedTime", 0L);
        fy = new LongPref("lastContactObserverDeletedTime", Long.valueOf(new Date().getTime()));
        fz = new BooleanPref("isDefaultPhoneApp", Boolean.FALSE);
        fA = new BooleanPref("hasPhoneRang", Boolean.FALSE);
        fB = new IntegerPref("lastXLocationForFloatingWidgetView", 0);
        fC = new IntegerPref("lastYLocationForFloatingWidgetView", 100);
        fD = new BooleanPref("seenInCallFloatingWidgetView", Boolean.FALSE);
        fE = new BooleanPref("answeringHorizontal", Boolean.valueOf(DeviceDetector.isSamsung()));
        fF = new LongPref("lastTimeUpdateToDefaultPhoneAppPopupWasShown", -1L);
        fG = new IntegerPref("showCallScreenEncouragementPopupShownCounter", 0);
        fH = new IntegerPref("drawOnScreenPopupShownCounter", 0);
        fI = new BooleanPref("wasGetSimStateBySlotIndexExceptionEverSent", Boolean.FALSE);
        fJ = new StringPref("vkAccessToken", "");
        fK = new StringPref("tokenAuth", "");
        fL = new IntegerPref("tokenSource", -1);
        fM = new BooleanPref("shouldShowIncognitoCallPopup", Boolean.TRUE);
        fN = new BooleanPref("shouldShowIncognitoPopup", Boolean.TRUE);
        fO = new BooleanPref("shouldshowIncognitoModeExplanationPopup", Boolean.TRUE);
        fP = new BooleanPref("contactListIncognitoPusherShown", Boolean.FALSE);
        fQ = new BooleanPref("hasMadeIncognitoCall", Boolean.FALSE);
        fR = new DatePref("showIncognitoPusherStartDate", new Date());
        fS = new DatePref("lastIncognitoCallLogCheckedTime", new Date());
        fT = new StringPref("currentTutorialPage", (String) null);
        fU = new StringPref("encodedTutorialPages", (String) null);
        fV = new DatePref("firstSeenTutorialWidgetTime", null);
        fW = new IntegerPref("lastXLocationForFloatingWidgetView", -1);
        fX = new IntegerPref("lastYLocationForFloatingWidgetView", -1);
        fY = new IntegerPref("welcomeTutorialWidgetStatus", 0);
        fZ = new DatePref("userEnteredMarketPlaceOrAdFreePlanPageDate", null);
        ga = new BooleanPref("noMediaFileCreatedForGlide", Boolean.FALSE);
        gb = new LongArray("favoriteLocation");
        gc = new BooleanPref("favoriteState", Boolean.FALSE);
        gd = new BooleanPref("showNoteBanner", Boolean.TRUE);
        ge = new IntegerPref("enterIntoMarketCounter", 0);
        gf = new BooleanPref("neverShowPromotionBanner", Boolean.FALSE);
        gg = new IntegerPref("openKeypadCounter", 0);
        gh = new BooleanPref("isKeypadPromotionsWidgetActive", Boolean.TRUE);
        gi = new LongArray("showKeypadBannerDaysArray");
        gj = new BooleanPref("useDebugAdUnits", Boolean.FALSE);
        gk = new BooleanPref("showRingingText", Boolean.FALSE);
        gl = new BooleanPref("forceSetRemoteConfigDefaults", Boolean.FALSE);
        gm = new BooleanPref("showCallLogStickBannerForFirst", Boolean.FALSE);
        gn = new BooleanPref("userClickOnStickyBanner", Boolean.FALSE);
        go = new BooleanPref("userClickOnDefaultPhoneStickyBanner", Boolean.FALSE);
        gp = new DatePref("userLastDateOfStickyBanner", new Date());
        gq = new DatePref("storeToolBarDate", new Date());
        gr = new BooleanPref("callAppFirstTimeSms", Boolean.TRUE);
        gs = new BooleanPref("callAppFirstTimeClipboard", Boolean.TRUE);
        gt = new BooleanPref("callAppFirstTimeCall", Boolean.TRUE);
        gu = new BooleanPref("callAppFirstTimeNotification", Boolean.TRUE);
        gv = new StringPref("firstTimeExperienceCallAppPlus", "012345678");
        gw = new BooleanPref("calAppFirstTimeExperience", Boolean.FALSE);
        gx = new BooleanPref("installReferrerCalled", Boolean.FALSE);
        gy = new BooleanPref("isShowRegistrationReminderServiceRegistered", Boolean.FALSE);
        gz = new BooleanPref("isConnectionChangedServiceRegistered", Boolean.FALSE);
        gA = new BooleanPref("isPowerConnectedServiceRegistered", Boolean.FALSE);
        gB = new BooleanPref("iRequestSyncRegistered", Boolean.FALSE);
        gC = new BooleanPref("enableAutomationTestFlow", Boolean.FALSE);
        gD = new IntegerPref("analyticsContactConfirm", 0);
        gE = new IntegerPref("analyticsSpammersReport", 0);
        gF = new IntegerPref("analyticsProfilePhotoChecked", 0);
        gG = new EnumPref<>("analyticsDatePicker", AnalyticsDatePickerManager.DatePicker.WEEK);
        gH = new DatePref("showInsightFlagDate", null);
        gI = new BooleanPref("needToShowInsightFlagAfterInstall", Boolean.TRUE);
        gJ = new BooleanPref("needToShowInsightFirstTimeDialog", Boolean.TRUE);
        gK = new BooleanPref("needToShowCommunityFirstTimeDialog", Boolean.TRUE);
        gL = new BooleanPref("needToGetMasterGift", Boolean.TRUE);
        gM = new BooleanPref("recorderTestFinished", null);
        gN = new BooleanPref("recorderTestFirstTimeExperience", Boolean.FALSE);
        gO = new BooleanPref("userClickedPVRIcon", Boolean.FALSE);
        gP = new EnumPref<>("contributaionLevel", CommunityCard.CommunityContributionLevel.INIT);
        gQ = new BooleanPref("firstTimeEnterWhiteColor", Boolean.TRUE);
        gR = new IntegerPref("contributionAutomation", 0);
        gS = new IntegerPref("howManyTimeUpdatePopUp", 0);
        gT = new StringPref[]{new StringPref("driveModeBluetoothAddress1", (String) null), new StringPref("driveModeBluetoothAddress2", (String) null), new StringPref("driveModeBluetoothAddress3", (String) null), new StringPref("driveModeBluetoothAddress4", (String) null), new StringPref("driveModeBluetoothAddress5", (String) null), new StringPref("driveModeBluetoothAddress6", (String) null)};
        gU = new BooleanPref("isInDriveMode", Boolean.FALSE);
        gV = new BooleanPref("isInDriveModeIncoming", Boolean.FALSE);
        gW = new BooleanPref("isInDriveModeOutgoing", Boolean.FALSE);
        gX = new IntegerPref("showCarModeOutGoingPopUpCounter", 0);
        gY = new IntegerPref("numberOfCallsDriveModeIncoming", 0);
        gZ = new IntegerPref("driveModeBluetoothConnectionCounter", 0);
        ha = new IntegerPref("driveModeBluetoothOverlayCounter", 0);
        hb = new BooleanPref("contactLookupDataSearchWithDelimUpdated_v96", Boolean.FALSE);
        hc = new BooleanPref("contactLookupDataDescriptionSearchWithDelimUpdated_v96", Boolean.FALSE);
        hd = new StringPref("lastContactsWithDelimNotUpdatedRatioPref_v96", "1");
        he = new LongPref("lastContactsWithDelimExtractedInfoNotUpdatedRatioPref_v96", 1L);
        hf = new StringPref("lastContactsWithDelimDescriptionNotUpdatedRatioPref_v96", "1");
        hg = new IntegerPref("animateAnalyticsCard", 0);
        hh = new IntegerPref("animateAnalyticsCardWhenExpandThreeTimes", 0);
        hi = new IntegerPref("firstTimePostCallCard", 0);
        hj = new BooleanPref("neverClickOnPostCall", Boolean.TRUE);
        hk = new IntegerPref("animateAnalyticsCardThreeTimes", 0);
        hl = new EnumPref<>("userDefaultIm", ContactAction.UNKNOWN);
        hm = new IntegerPref("notContactBusinessPostCallCard", 0);
        hn = new IntegerPref("notContactPostCallCard", 0);
        ho = new IntegerPref("showIncomingPhoneVerificationDialog", 0);
        hp = new IntegerPref("postCallPhoneVerificationDialogCounter", 0);
        hq = new BooleanPref("needToShowPostCallPhoneVerificationDialog", Boolean.TRUE);
        hr = new StringPref("referAndEarnLinkCode", "");
        hs = new IntegerPref("referAndEarnPoints", 0);
        ht = new IntegerPref("referAndEarnShowPoints", 0);
        hu = new BooleanPref("alwaysShowReferAndEarnCard", Boolean.FALSE);
        hv = new IntegerPref("referAndEarnCardCounter", 0);
        hw = new BooleanPref("ignoreGoogleMaps", Boolean.FALSE);
        hx = new BooleanPref("isCDInsightsCardLastOpen", Boolean.TRUE);
        hy = new EnumPref<>("whoViewedMyProfileNotificationTiming", WhoViewedMyProfileDataManager.NotificationWhoViewedMyProfile.INSTANT);
        hz = new BooleanPref("whoViewedMyProfileNotificationEnabled", Boolean.TRUE);
        hA = new BooleanPref("privateMode", Boolean.FALSE);
        hB = new IntegerPref("whoViewedMyProfileCounter", 0);
        hC = new DatePref("whoViewedMyProfileDailyLastScheduled", null);
        hD = new LongPref("lastSeenViewerProfile", 0L);
        hE = new BooleanPref("whoViewedIgnoreRules", Boolean.FALSE);
        hF = new BooleanPref("whoViewedShowGraphDebug", Boolean.FALSE);
        hG = new StringPref("dropboxAccessToken", "");
        hH = new StringPref("googleDriveSessionId", "");
        hI = new BooleanPref("notUseCallMeAgain", Boolean.FALSE);
        hJ = new DatePref("lastBackupDate", null);
        hK = new EnumPref<>("backupVia", BackupViaType.UN_KNOWN);
        hL = new IntegerPref("backupIntervalInDays", Integer.valueOf(BackupIntervalPeriod.MONTH.getDaysInterval()));
        hM = new BooleanPref("backupContacts", Boolean.TRUE);
        hN = new BooleanPref("backupCallLog", Boolean.TRUE);
        hO = new BooleanPref("backupVideoRingTones", Boolean.FALSE);
        hP = new BooleanPref("backupRecording", Boolean.FALSE);
        hQ = new BooleanPref("hasBackupPlan", Boolean.FALSE);
        hR = new BooleanPref("showBackupSetupAfterBuyPlan", Boolean.FALSE);
        hS = new BooleanPref("completeBackupSettings", Boolean.FALSE);
        hT = new IntegerPref("backupRetriesCount", 0);
        hU = new BooleanPref("enableDeveloperBackupPlan", Boolean.FALSE);
        hV = new BooleanPref("hasScheduleBackupJob", Boolean.FALSE);
        hW = new ArrayPref("completeBackupOnce");
        hX = new DatePref("lastBackupWorkerStartedDate", null);
        hY = new DatePref("callRecordingDateOfStickyBanner", null);
        hZ = new DatePref("callRecordingDateOfStickyBannerAfterRevoke", null);
        ia = new DatePref("defaultDialerCalllogStickyBanner", null);
        ib = new DatePref("defaultDialerCalllogStickyBannerAfterRevoke", null);
        ic = new BooleanPref("userSawDefaultDialerSticky", Boolean.FALSE);
        id = new BooleanPref("userSawCallRecorderSticky", Boolean.FALSE);
        ie = new BooleanPref("callAppPlusStickyClicked", Boolean.FALSE);
    }
}
