package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
/* loaded from: classes-dex2jar.jar:com/google/android/gms/common/api/internal/zaca.class */
public final class zaca<R extends Result> extends PendingResult<R> {
    @Override // com.google.android.gms.common.api.PendingResult
    /* renamed from: a */
    public final void mo17508a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
