package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import com.google.android.gms.ads.internal.util.zzf;
import com.google.android.gms.internal.ads.eht;
import java.util.Map;
import java.util.Set;
/* loaded from: classes3-dex2jar.jar:com/google/android/gms/internal/ads/aht.class */
final class aht extends cau {
    private dsv<bom> A;
    private dsv<bpk> B;
    private dsv<bnv> C;
    private dsv<cbs> D;
    private dsv<Context> E;
    private dsv<ApplicationInfo> F;
    private dsv<PackageInfo> G;
    private dsv<dbt<String>> H;
    private dsv<zzf> I;
    private dsv<cpo> J;
    private dsv<yc> K;
    private dsv<apf> L;
    private dsv<String> M;
    private dsv<cqm> N;
    private dsv<cde> O;
    private dsv<cch> P;
    private dsv<ccc> Q;
    private dsv<Set<String>> R;
    private dsv<cfk> S;
    private dsv<ccp> T;
    private dsv<cek> U;
    private dsv V;
    private dsv<Bundle> W;
    private dsv<cfs> X;
    private dsv<cee> Y;
    private dsv<cfr> Z;

    /* renamed from: a  reason: collision with root package name */
    private dsv<Context> f23373a;
    private final /* synthetic */ ago aA;
    private dsv<cmp> aa;
    private dsv<cgq> ab;
    private dsv<ccz> ac;
    private dsv<cdi> ad;
    private dsv<dbt<String>> ae;
    private dsv<cce> af;
    private dsv<cgl> ag;
    private dsv<chl> ah;
    private dsv<cex> ai;
    private dsv<cgh> aj;
    private dsv<ceo> ak;
    private dsv<cfb> al;
    private dsv<cda> am;
    private dsv<String> an;
    private dsv<bym> ao;
    private dsv<cgc> ap;
    private dsv<cgr> aq;
    private dsv<clq> ar;
    private dsv<cdr> as;
    private dsv<String> at;
    private dsv<cfx> au;
    private dsv<cdy> av;
    private dsv<Set<chb<? extends cgy<Bundle>>>> aw;
    private dsv<cha<Bundle>> ax;
    private dsv<aqs> ay;
    private dsv<dbt<cbt>> az;

    /* renamed from: b  reason: collision with root package name */
    private dsv<String> f23374b;

    /* renamed from: c  reason: collision with root package name */
    private dsv<eht.a.EnumC0477a> f23375c;

    /* renamed from: d  reason: collision with root package name */
    private dsv<String> f23376d;
    private dsv<ehk> e;
    private dsv<bkt> f;
    private dsv<bkt> g;
    private dsv<Map<ctj, bkt>> h;
    private dsv<bkr> i;
    private dsv<Set<ayi<cto>>> j;
    private dsv<yo> k;
    private dsv<blf> l;
    private dsv m;
    private dsv<blm> n;
    private dsv o;
    private dsv<ctz> p;
    private dsv<bqn> q;
    private dsv<ayi<cto>> r;
    private dsv<bmf> s;
    private dsv<Set<ayi<cto>>> t;
    private dsv<brb> u;
    private dsv<brc> v;
    private dsv<ayi<cto>> w;
    private dsv<Set<ayi<cto>>> x;
    private dsv y;
    private dsv<cti> z;

    private aht(ago agoVar, cbj cbjVar, aow aowVar, blv blvVar, aqz aqzVar, cqo cqoVar, cmp cmpVar, clq clqVar) {
        dsv dsvVar;
        bnq bnqVar;
        dsv dsvVar2;
        dsv dsvVar3;
        bjw bjwVar;
        bjy bjyVar;
        csh cshVar;
        dsv dsvVar4;
        dsv dsvVar5;
        bld bldVar;
        dsv dsvVar6;
        bql bqlVar;
        csh cshVar2;
        dsv dsvVar7;
        dsv dsvVar8;
        csh cshVar3;
        bra braVar;
        csh cshVar4;
        csh cshVar5;
        dsv dsvVar9;
        dsv dsvVar10;
        dsv dsvVar11;
        dsv dsvVar12;
        agi agiVar;
        dsv dsvVar13;
        dsv dsvVar14;
        dsv dsvVar15;
        dsv dsvVar16;
        csh cshVar6;
        csh cshVar7;
        dsv dsvVar17;
        dsv dsvVar18;
        dsv dsvVar19;
        dsv dsvVar20;
        dsv dsvVar21;
        dsv dsvVar22;
        dsv dsvVar23;
        dsv dsvVar24;
        dsv dsvVar25;
        dsv dsvVar26;
        dsv dsvVar27;
        csh cshVar8;
        csh cshVar9;
        csh cshVar10;
        csh cshVar11;
        dsv dsvVar28;
        csh cshVar12;
        dsv dsvVar29;
        csh cshVar13;
        csh cshVar14;
        csh cshVar15;
        dsv dsvVar30;
        csh cshVar16;
        csh cshVar17;
        dsv dsvVar31;
        csh cshVar18;
        csh cshVar19;
        csh cshVar20;
        dsv dsvVar32;
        csh cshVar21;
        dsv dsvVar33;
        dsv dsvVar34;
        csh cshVar22;
        dsv dsvVar35;
        dsv dsvVar36;
        csh cshVar23;
        bnn bnnVar;
        csh cshVar24;
        dsv dsvVar37;
        dsv dsvVar38;
        dsv dsvVar39;
        csh cshVar25;
        dsv dsvVar40;
        bnl bnlVar;
        this.aA = agoVar;
        dsvVar = agoVar.f;
        cqq a2 = cqq.a(cqoVar, dsvVar);
        this.f23373a = a2;
        this.f23374b = bno.a(a2);
        this.f23375c = dsj.a(new cbn(cbjVar));
        bnqVar = bnt.f24764a;
        this.f23376d = dsj.a(bnqVar);
        dsvVar2 = agoVar.f;
        dsv<String> dsvVar41 = this.f23374b;
        dsvVar3 = agoVar.g;
        this.e = dsj.a(bjn.a(dsvVar2, dsvVar41, dsvVar3, this.f23375c, this.f23376d));
        bjwVar = bjv.f24572a;
        this.f = dsj.a(bjwVar);
        bjyVar = bjx.f24573a;
        this.g = dsj.a(bjyVar);
        dsk a3 = ((dsm) ((dsm) dsk.a(2).a(ctj.SIGNALS, this.f)).a(ctj.RENDERER, this.g)).a();
        this.h = a3;
        this.i = bks.a(this.e, a3);
        cshVar = csk.f26340a;
        this.j = dsj.a(bka.a(cshVar, this.i));
        dsvVar4 = agoVar.Q;
        this.k = cqt.a(cqoVar, dsvVar4);
        dsvVar5 = agoVar.w;
        this.l = dsj.a(ble.a(dsvVar5, this.k));
        dst a4 = dsr.a(1, 0);
        bldVar = blc.f24627a;
        dsr a5 = a4.a(bldVar).a();
        this.m = a5;
        dsv<blf> dsvVar42 = this.l;
        dsvVar6 = agoVar.p;
        this.n = dsj.a(blo.a(dsvVar42, a5, dsvVar6));
        dst a6 = dsr.a(1, 0);
        bqlVar = bqk.f24894a;
        this.o = a6.a(bqlVar).a();
        dsv<ctz> a7 = dsj.a(bns.a(this.f23376d));
        this.p = a7;
        this.q = dsj.a(bqp.a(this.o, a7));
        dsv<blm> dsvVar43 = this.n;
        cshVar2 = csk.f26340a;
        this.r = dsj.a(bla.a(dsvVar43, cshVar2, this.q));
        dsvVar7 = agoVar.R;
        dsvVar8 = agoVar.G;
        dsv<bmf> a8 = dsj.a(bmj.a(dsvVar7, dsvVar8));
        this.s = a8;
        cshVar3 = csk.f26340a;
        this.t = bmg.a(blvVar, a8, cshVar3);
        braVar = brd.f24931a;
        dsv<brb> a9 = dsj.a(braVar);
        this.u = a9;
        brf a10 = brf.a(a9);
        this.v = a10;
        cshVar4 = csk.f26340a;
        this.w = dsj.a(bqq.a(a10, cshVar4));
        dsr a11 = dsr.a(2, 2).b(this.j).a(this.r).b(this.t).a(this.w).a();
        this.x = a11;
        this.y = ctq.a(a11);
        cshVar5 = csk.f26340a;
        dsvVar9 = agoVar.l;
        this.z = dsj.a(ctr.a(cshVar5, dsvVar9, this.y));
        dsvVar10 = agoVar.f;
        this.A = new boo(dsvVar10);
        dsvVar11 = agoVar.f;
        dsvVar12 = agoVar.n;
        agiVar = agm.f23250a;
        dsvVar13 = agoVar.ab;
        dsvVar14 = agoVar.ac;
        dsvVar15 = agoVar.ad;
        this.B = bqa.a(dsvVar11, dsvVar12, agiVar, dsvVar13, dsvVar14, dsvVar15);
        dsvVar16 = agoVar.l;
        cshVar6 = csk.f26340a;
        this.C = new bnx(dsvVar16, cshVar6, this.A, this.B);
        cshVar7 = csk.f26340a;
        this.D = new cbu(cshVar7, this.C);
        dsv<Context> a12 = dsj.a(ara.a(aqzVar, this.f23373a));
        this.E = a12;
        bni a13 = bni.a(a12);
        this.F = a13;
        this.G = dsj.a(bnp.a(this.E, a13));
        this.H = dsj.a(bnf.a(this.z, this.E));
        dsvVar17 = agoVar.Q;
        this.I = cqr.a(cqoVar, dsvVar17);
        this.J = ard.a(aqzVar);
        dsvVar18 = agoVar.p;
        this.K = dsj.a(apc.a(dsvVar18, this.k, this.J));
        dsvVar19 = agoVar.p;
        dsv<apf> a14 = dsj.a(ape.a(dsvVar19, this.K));
        this.L = a14;
        this.M = arb.a(aqzVar, a14);
        this.N = dsj.a(cqp.a(this.f23373a, this.k));
        dsv<String> dsvVar44 = this.M;
        dsvVar20 = agoVar.v;
        this.O = cdg.a(dsvVar44, dsvVar20, this.L, this.N, this.J);
        dsvVar21 = agoVar.U;
        dsv<cpo> dsvVar45 = this.J;
        dsv<Context> dsvVar46 = this.f23373a;
        dsvVar22 = agoVar.Q;
        this.P = ccj.a(dsvVar21, dsvVar45, dsvVar46, dsvVar22);
        this.Q = ccb.a(this.J);
        this.R = dsj.a(new cbp(cbjVar));
        dsvVar23 = agoVar.S;
        this.S = cfm.a(dsvVar23, this.f23373a, this.R);
        dsvVar24 = agoVar.S;
        dsvVar25 = agoVar.r;
        dsvVar26 = agoVar.C;
        dsvVar27 = agoVar.V;
        this.T = ccx.a(dsvVar24, dsvVar25, dsvVar26, dsvVar27);
        dsv<Context> dsvVar47 = this.E;
        cshVar8 = csk.f26340a;
        this.U = cem.a(dsvVar47, cshVar8);
        this.V = cco.a(this.R);
        this.W = arc.a(aqzVar);
        cshVar9 = csk.f26340a;
        this.X = cfu.a(cshVar9, this.W);
        dsv<Context> dsvVar48 = this.f23373a;
        cshVar10 = csk.f26340a;
        this.Y = cei.a(dsvVar48, cshVar10);
        this.Z = cfq.a(this.F, this.G);
        dsi b2 = dsl.b(null);
        this.aa = b2;
        this.ab = cgs.a(b2);
        cshVar11 = csk.f26340a;
        dsv<cpo> dsvVar49 = this.J;
        dsvVar28 = agoVar.g;
        this.ac = cdb.a(cshVar11, dsvVar49, dsvVar28);
        cshVar12 = csk.f26340a;
        this.ad = cdk.a(cshVar12, this.f23373a);
        dsvVar29 = agoVar.H;
        dsv<Context> dsvVar50 = this.f23373a;
        cshVar13 = csk.f26340a;
        dsv<dbt<String>> a15 = dsj.a(bng.a(dsvVar29, dsvVar50, cshVar13));
        this.ae = a15;
        cshVar14 = csk.f26340a;
        this.af = ccf.a(a15, cshVar14);
        cshVar15 = csk.f26340a;
        dsv<Context> dsvVar51 = this.f23373a;
        dsvVar30 = agoVar.g;
        this.ag = cgn.a(cshVar15, dsvVar51, dsvVar30);
        cshVar16 = csk.f26340a;
        this.ah = chn.a(cshVar16, this.f23373a);
        cshVar17 = csk.f26340a;
        this.ai = cez.a(cshVar17);
        dsvVar31 = agoVar.D;
        cshVar18 = csk.f26340a;
        this.aj = cgj.a(dsvVar31, cshVar18, this.f23373a);
        cshVar19 = csk.f26340a;
        this.ak = ceq.a(cshVar19);
        cshVar20 = csk.f26340a;
        dsvVar32 = agoVar.Y;
        this.al = cfd.a(cshVar20, dsvVar32);
        cshVar21 = csk.f26340a;
        dsvVar33 = agoVar.Q;
        this.am = cdf.a(cshVar21, dsvVar33);
        this.an = dsj.a(new cbm(cbjVar));
        dsvVar34 = agoVar.r;
        this.ao = dsj.a(byl.a(dsvVar34));
        cshVar22 = csk.f26340a;
        dsvVar35 = agoVar.l;
        dsv<String> dsvVar52 = this.an;
        dsvVar36 = agoVar.t;
        this.ap = cgf.a(cshVar22, dsvVar35, dsvVar52, dsvVar36, this.E, this.J, this.ao);
        cshVar23 = csk.f26340a;
        this.aq = cgz.a(cshVar23, this.f23373a);
        dsi b3 = dsl.b(null);
        this.ar = b3;
        this.as = cdu.a(b3);
        bnnVar = bnm.f24758a;
        dsv<String> a16 = dsj.a(bnnVar);
        this.at = a16;
        this.au = cga.a(this.f23376d, a16);
        cshVar24 = csk.f26340a;
        dsvVar37 = agoVar.E;
        this.av = cea.a(cshVar24, dsvVar37, this.J, this.an);
        dst a17 = dsr.a(28, 0).a(this.O).a(this.P).a(this.Q).a(this.S).a(this.T).a(this.U).a(this.V).a(this.X).a(this.Y).a(this.Z).a(this.ab).a(this.ac).a(this.ad).a(this.af).a(this.ag);
        dsvVar38 = agoVar.U;
        dst a18 = a17.a(dsvVar38).a(this.ah);
        dsvVar39 = agoVar.X;
        this.aw = a18.a(dsvVar39).a(this.ai).a(this.aj).a(this.ak).a(this.al).a(this.am).a(this.ap).a(this.aq).a(this.as).a(this.au).a(this.av).a();
        cshVar25 = csk.f26340a;
        this.ax = chf.a(cshVar25, this.aw);
        dsv<cti> dsvVar53 = this.z;
        dsvVar40 = agoVar.g;
        dsv<ApplicationInfo> dsvVar54 = this.F;
        dsv<String> dsvVar55 = this.f23374b;
        bnlVar = bnk.f24757a;
        aqu a19 = aqu.a(dsvVar53, dsvVar40, dsvVar54, dsvVar55, bnlVar, this.G, this.H, this.I, this.f23376d, this.ax);
        this.ay = a19;
        this.az = dsj.a(new cbo(this.z, this.D, a19));
    }

    @Override // com.google.android.gms.internal.ads.cau
    public final dbt<cbt> a() {
        return this.az.a();
    }
}
