package com.google.android.gms.internal.ads;

import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.common.internal.safeparcel.a;
import java.util.Collections;
import java.util.List;
/* loaded from: classes3-dex2jar.jar:com/google/android/gms/internal/ads/zzats.class */
public final class zzats extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzats> CREATOR = new si();
    private final int errorCode;
    private final int orientation;
    private final int versionCode;
    private final zzatu zzbot;
    private final boolean zzbpv;
    private final boolean zzbpw;
    private final boolean zzbsb;
    private final String zzbwe;
    private final boolean zzcit;
    private final boolean zzciu;
    private final List<String> zzdna;
    private final List<String> zzdnb;
    private final List<String> zzdnc;
    private final List<String> zzdne;
    private final boolean zzdnf;
    private final long zzdnh;
    private final String zzdug;
    private final boolean zzdvu;
    private String zzdwh;
    private final boolean zzdwt;
    private String zzdxg;
    private final long zzdxh;
    private final boolean zzdxi;
    private final long zzdxj;
    private final List<String> zzdxk;
    private final String zzdxl;
    private final long zzdxm;
    private final String zzdxn;
    private final boolean zzdxo;
    private final String zzdxp;
    private final String zzdxq;
    private final boolean zzdxr;
    private final boolean zzdxs;
    private final boolean zzdxt;
    private zzaue zzdxu;
    private String zzdxv;
    private final zzavy zzdxw;
    private final List<String> zzdxx;
    private final List<String> zzdxy;
    private final boolean zzdxz;
    private final String zzdya;
    private final zzaxn zzdyb;
    private final String zzdyc;
    private final boolean zzdyd;
    private Bundle zzdye;
    private final int zzdyf;
    private final boolean zzdyg;
    private final String zzdyh;
    private String zzdyi;
    private boolean zzdyj;
    private boolean zzdyk;

    /* JADX INFO: Access modifiers changed from: package-private */
    public zzats(int i, String str, String str2, List<String> list, int i2, List<String> list2, long j, boolean z, long j2, List<String> list3, long j3, int i3, String str3, long j4, String str4, boolean z2, String str5, String str6, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, zzaue zzaueVar, String str7, String str8, boolean z8, boolean z9, zzavy zzavyVar, List<String> list4, List<String> list5, boolean z10, zzatu zzatuVar, String str9, List<String> list6, boolean z11, String str10, zzaxn zzaxnVar, String str11, boolean z12, boolean z13, Bundle bundle, boolean z14, int i4, boolean z15, List<String> list7, boolean z16, String str12, String str13, boolean z17, boolean z18) {
        zzaul zzaulVar;
        this.versionCode = i;
        this.zzdug = str;
        this.zzdxg = str2;
        List<String> list8 = null;
        this.zzdna = list != null ? Collections.unmodifiableList(list) : null;
        this.errorCode = i2;
        this.zzdnb = list2 != null ? Collections.unmodifiableList(list2) : null;
        this.zzdxh = j;
        this.zzdxi = z;
        this.zzdxj = j2;
        this.zzdxk = list3 != null ? Collections.unmodifiableList(list3) : null;
        this.zzdnh = j3;
        this.orientation = i3;
        this.zzdxl = str3;
        this.zzdxm = j4;
        this.zzdxn = str4;
        this.zzdxo = z2;
        this.zzdxp = str5;
        this.zzdxq = str6;
        this.zzdxr = z3;
        this.zzbsb = z4;
        this.zzdvu = z5;
        this.zzdxs = z6;
        this.zzdyd = z12;
        this.zzdxt = z7;
        this.zzdxu = zzaueVar;
        this.zzdxv = str7;
        this.zzbwe = str8;
        if (this.zzdxg == null && zzaueVar != null && (zzaulVar = (zzaul) zzaueVar.zza(zzaul.CREATOR)) != null && !TextUtils.isEmpty(zzaulVar.zzdyw)) {
            this.zzdxg = zzaulVar.zzdyw;
        }
        this.zzcit = z8;
        this.zzciu = z9;
        this.zzdxw = zzavyVar;
        this.zzdxx = list4;
        this.zzdxy = list5;
        this.zzdxz = z10;
        this.zzbot = zzatuVar;
        this.zzdwh = str9;
        this.zzdne = list6;
        this.zzdnf = z11;
        this.zzdya = str10;
        this.zzdyb = zzaxnVar;
        this.zzdyc = str11;
        this.zzdwt = z13;
        this.zzdye = bundle;
        this.zzbpv = z14;
        this.zzdyf = i4;
        this.zzdyg = z15;
        this.zzdnc = list7 != null ? Collections.unmodifiableList(list7) : list8;
        this.zzbpw = z16;
        this.zzdyh = str12;
        this.zzdyi = str13;
        this.zzdyj = z17;
        this.zzdyk = z18;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int a2 = a.a(parcel, 20293);
        a.a(parcel, 1, this.versionCode);
        a.a(parcel, 2, this.zzdug, false);
        a.a(parcel, 3, this.zzdxg, false);
        a.a(parcel, 4, this.zzdna);
        a.a(parcel, 5, this.errorCode);
        a.a(parcel, 6, this.zzdnb);
        a.a(parcel, 7, this.zzdxh);
        a.a(parcel, 8, this.zzdxi);
        a.a(parcel, 9, this.zzdxj);
        a.a(parcel, 10, this.zzdxk);
        a.a(parcel, 11, this.zzdnh);
        a.a(parcel, 12, this.orientation);
        a.a(parcel, 13, this.zzdxl, false);
        a.a(parcel, 14, this.zzdxm);
        a.a(parcel, 15, this.zzdxn, false);
        a.a(parcel, 18, this.zzdxo);
        a.a(parcel, 19, this.zzdxp, false);
        a.a(parcel, 21, this.zzdxq, false);
        a.a(parcel, 22, this.zzdxr);
        a.a(parcel, 23, this.zzbsb);
        a.a(parcel, 24, this.zzdvu);
        a.a(parcel, 25, this.zzdxs);
        a.a(parcel, 26, this.zzdxt);
        a.a(parcel, 28, this.zzdxu, i, false);
        a.a(parcel, 29, this.zzdxv, false);
        a.a(parcel, 30, this.zzbwe, false);
        a.a(parcel, 31, this.zzcit);
        a.a(parcel, 32, this.zzciu);
        a.a(parcel, 33, this.zzdxw, i, false);
        a.a(parcel, 34, this.zzdxx);
        a.a(parcel, 35, this.zzdxy);
        a.a(parcel, 36, this.zzdxz);
        a.a(parcel, 37, this.zzbot, i, false);
        a.a(parcel, 39, this.zzdwh, false);
        a.a(parcel, 40, this.zzdne);
        a.a(parcel, 42, this.zzdnf);
        a.a(parcel, 43, this.zzdya, false);
        a.a(parcel, 44, this.zzdyb, i, false);
        a.a(parcel, 45, this.zzdyc, false);
        a.a(parcel, 46, this.zzdyd);
        a.a(parcel, 47, this.zzdwt);
        a.a(parcel, 48, this.zzdye, false);
        a.a(parcel, 49, this.zzbpv);
        a.a(parcel, 50, this.zzdyf);
        a.a(parcel, 51, this.zzdyg);
        a.a(parcel, 52, this.zzdnc);
        a.a(parcel, 53, this.zzbpw);
        a.a(parcel, 54, this.zzdyh, false);
        a.a(parcel, 55, this.zzdyi, false);
        a.a(parcel, 56, this.zzdyj);
        a.a(parcel, 57, this.zzdyk);
        a.b(parcel, a2);
    }
}
