package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.common.internal.safeparcel.a;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
/* loaded from: classes3-dex2jar.jar:com/google/android/gms/internal/ads/zzatq.class */
public final class zzatq extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzatq> CREATOR = new sh();
    private final ApplicationInfo applicationInfo;
    private final int versionCode;
    private final zzbar zzbpx;
    private final zzvt zzbpy;
    private final float zzbsn;
    private final String zzbvf;
    private final String zzckb;
    private final boolean zzdnf;
    private final zzaei zzdpr;
    private final List<String> zzdps;
    private final int zzdrr;
    private final int zzdrs;
    private final Bundle zzdvm;
    private final zzvq zzdvn;
    private final PackageInfo zzdvo;
    private final String zzdvp;
    private final String zzdvq;
    private final Bundle zzdvr;
    private final int zzdvs;
    private final Bundle zzdvt;
    private final boolean zzdvu;
    private final String zzdvv;
    private final long zzdvw;
    private final String zzdvx;
    private final List<String> zzdvy;
    private final String zzdvz;
    private final List<String> zzdwa;
    private final long zzdwb;
    private final String zzdwc;
    private final float zzdwd;
    private final int zzdwe;
    private final int zzdwf;
    private final boolean zzdwg;
    private final String zzdwh;
    private final boolean zzdwi;
    private final String zzdwj;
    private final int zzdwk;
    private final Bundle zzdwl;
    private final String zzdwm;
    private final zzzj zzdwn;
    private final boolean zzdwo;
    private final Bundle zzdwp;
    private final String zzdwq;
    private final String zzdwr;
    private final String zzdws;
    private final boolean zzdwt;
    private final List<Integer> zzdwu;
    private final String zzdwv;
    private final List<String> zzdww;
    private final int zzdwx;
    private final boolean zzdwy;
    private final boolean zzdwz;
    private final boolean zzdxa;
    private final ArrayList<String> zzdxb;
    private final String zzdxc;
    private final zzajy zzdxd;
    private final String zzdxe;
    private final Bundle zzdxf;

    /* JADX INFO: Access modifiers changed from: package-private */
    public zzatq(int i, Bundle bundle, zzvq zzvqVar, zzvt zzvtVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, zzbar zzbarVar, Bundle bundle2, int i2, List<String> list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List<String> list2, String str7, zzaei zzaeiVar, List<String> list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzzj zzzjVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List<Integer> list4, String str15, List<String> list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList<String> arrayList, String str16, zzajy zzajyVar, String str17, Bundle bundle6) {
        this.versionCode = i;
        this.zzdvm = bundle;
        this.zzdvn = zzvqVar;
        this.zzbpy = zzvtVar;
        this.zzbvf = str;
        this.applicationInfo = applicationInfo;
        this.zzdvo = packageInfo;
        this.zzdvp = str2;
        this.zzdvq = str3;
        this.zzckb = str4;
        this.zzbpx = zzbarVar;
        this.zzdvr = bundle2;
        this.zzdvs = i2;
        this.zzdps = list;
        this.zzdwa = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.zzdvt = bundle3;
        this.zzdvu = z;
        this.zzdrr = i3;
        this.zzdrs = i4;
        this.zzbsn = f;
        this.zzdvv = str5;
        this.zzdvw = j;
        this.zzdvx = str6;
        this.zzdvy = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.zzdvz = str7;
        this.zzdpr = zzaeiVar;
        this.zzdwb = j2;
        this.zzdwc = str8;
        this.zzdwd = f2;
        this.zzdwi = z2;
        this.zzdwe = i5;
        this.zzdwf = i6;
        this.zzdwg = z3;
        this.zzdwh = str9;
        this.zzdwj = str10;
        this.zzdnf = z4;
        this.zzdwk = i7;
        this.zzdwl = bundle4;
        this.zzdwm = str11;
        this.zzdwn = zzzjVar;
        this.zzdwo = z5;
        this.zzdwp = bundle5;
        this.zzdwq = str12;
        this.zzdwr = str13;
        this.zzdws = str14;
        this.zzdwt = z6;
        this.zzdwu = list4;
        this.zzdwv = str15;
        this.zzdww = list5;
        this.zzdwx = i8;
        this.zzdwy = z7;
        this.zzdwz = z8;
        this.zzdxa = z9;
        this.zzdxb = arrayList;
        this.zzdxc = str16;
        this.zzdxd = zzajyVar;
        this.zzdxe = str17;
        this.zzdxf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int a2 = a.a(parcel, 20293);
        a.a(parcel, 1, this.versionCode);
        a.a(parcel, 2, this.zzdvm, false);
        a.a(parcel, 3, this.zzdvn, i, false);
        a.a(parcel, 4, this.zzbpy, i, false);
        a.a(parcel, 5, this.zzbvf, false);
        a.a(parcel, 6, this.applicationInfo, i, false);
        a.a(parcel, 7, this.zzdvo, i, false);
        a.a(parcel, 8, this.zzdvp, false);
        a.a(parcel, 9, this.zzdvq, false);
        a.a(parcel, 10, this.zzckb, false);
        a.a(parcel, 11, this.zzbpx, i, false);
        a.a(parcel, 12, this.zzdvr, false);
        a.a(parcel, 13, this.zzdvs);
        a.a(parcel, 14, this.zzdps);
        a.a(parcel, 15, this.zzdvt, false);
        a.a(parcel, 16, this.zzdvu);
        a.a(parcel, 18, this.zzdrr);
        a.a(parcel, 19, this.zzdrs);
        a.a(parcel, 20, this.zzbsn);
        a.a(parcel, 21, this.zzdvv, false);
        a.a(parcel, 25, this.zzdvw);
        a.a(parcel, 26, this.zzdvx, false);
        a.a(parcel, 27, this.zzdvy);
        a.a(parcel, 28, this.zzdvz, false);
        a.a(parcel, 29, this.zzdpr, i, false);
        a.a(parcel, 30, this.zzdwa);
        a.a(parcel, 31, this.zzdwb);
        a.a(parcel, 33, this.zzdwc, false);
        a.a(parcel, 34, this.zzdwd);
        a.a(parcel, 35, this.zzdwe);
        a.a(parcel, 36, this.zzdwf);
        a.a(parcel, 37, this.zzdwg);
        a.a(parcel, 39, this.zzdwh, false);
        a.a(parcel, 40, this.zzdwi);
        a.a(parcel, 41, this.zzdwj, false);
        a.a(parcel, 42, this.zzdnf);
        a.a(parcel, 43, this.zzdwk);
        a.a(parcel, 44, this.zzdwl, false);
        a.a(parcel, 45, this.zzdwm, false);
        a.a(parcel, 46, this.zzdwn, i, false);
        a.a(parcel, 47, this.zzdwo);
        a.a(parcel, 48, this.zzdwp, false);
        a.a(parcel, 49, this.zzdwq, false);
        a.a(parcel, 50, this.zzdwr, false);
        a.a(parcel, 51, this.zzdws, false);
        a.a(parcel, 52, this.zzdwt);
        List<Integer> list = this.zzdwu;
        if (list != null) {
            int a3 = a.a(parcel, 53);
            int size = list.size();
            parcel.writeInt(size);
            for (int i2 = 0; i2 < size; i2++) {
                parcel.writeInt(list.get(i2).intValue());
            }
            a.b(parcel, a3);
        }
        a.a(parcel, 54, this.zzdwv, false);
        a.a(parcel, 55, this.zzdww);
        a.a(parcel, 56, this.zzdwx);
        a.a(parcel, 57, this.zzdwy);
        a.a(parcel, 58, this.zzdwz);
        a.a(parcel, 59, this.zzdxa);
        a.a(parcel, 60, this.zzdxb);
        a.a(parcel, 61, this.zzdxc, false);
        a.a(parcel, 63, this.zzdxd, i, false);
        a.a(parcel, 64, this.zzdxe, false);
        a.a(parcel, 65, this.zzdxf, false);
        a.b(parcel, a2);
    }
}
